import { PrelimsAnalysisView } from '@/components/analise/PrelimsAnalysisView';
import type { PrelimsAnalise } from '@/types/analise';

const analise: PrelimsAnalise = {
  id: 'mullins-vs-carolina',
  evento_id: null,
  slug: 'mullins-vs-carolina',
  titulo: 'Mullins vs Carolina',
  subtitulo: null,
  lutador1_id: null,
  lutador2_id: null,
  artigo_conteudo: '',
  tactical_breakdown: {
    stats: [],
    radarData: [],
    taleOfTape: {
      fighter1: { altura: '', envergadura: '', idade: 0, academia: '' },
      fighter2: { altura: '', envergadura: '', idade: 0, academia: '' },
    },
    pathsToVictory: { fighter1: [], fighter2: [] },
    dangerZones: [],
  },
  fight_prediction: {
    predictedWinner: 'fighter2',
    predictedMethod: 'Decisao Unanime',
    confidence: 'MEDIA',
    fighter1Scenarios: [],
    fighter2Scenarios: [],
    keyFactors: [],
    xFactor: { title: '', description: '' },
  },
  fighter1_info: {
    nome: 'Melissa Mullins',
    record: '7-2-0',
    ultimasLutas: [],
  },
  fighter2_info: {
    nome: 'Luana Carolina',
    record: '11-5-0',
    ultimasLutas: [],
  },
  evento_nome: 'UFC Fight Night: Evloev vs Murphy',
  evento_data: '21 de Marco, 2026',
  evento_local: 'The O2 Arena, Londres, Reino Unido',
  categoria_peso: 'Peso Galo Feminino (135 lbs)',
  num_rounds: 3,
  is_titulo: false,
  broadcast: null,
  status: 'published',
  analysis_type: 'prelims',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),

  prelims_analysis: {
    hero: {
      evento_nome: 'UFC Fight Night: Evloev vs Murphy',
      evento_data: '21 de Marco, 2026',
      categoria_peso: 'Peso Galo Feminino (135 lbs)',
      num_rounds: 3,
      is_titulo: false,
      fighter1: {
        nome: 'Mullins',
        record: '7-2-0',
        ranking: undefined,
      },
      fighter2: {
        nome: 'Carolina',
        record: '11-5-0',
        ranking: undefined,
      },
    },

    comparacao_estatistica: {
      stats: [
        {
          label: 'Sig. Strikes por Minuto',
          valueA: 3.80,
          valueB: 4.65,
          maxVal: 7,
          format: 'decimal',
          note: 'Carolina tem volume superior de strikes, quase 5 golpes significativos por minuto',
        },
        {
          label: 'Precisao de Strikes (%)',
          valueA: 44,
          valueB: 50,
          maxVal: 100,
          format: 'percent',
          note: 'Carolina conecta metade dos golpes, precisao acima da media da divisao',
        },
        {
          label: 'Strikes Absorvidos/Min',
          valueA: 3.60,
          valueB: 4.00,
          maxVal: 7,
          format: 'decimal',
          reverseWinner: true,
          note: 'Mullins absorve menos golpes, indicando boa movimentacao defensiva',
        },
        {
          label: 'Defesa de Strikes (%)',
          valueA: 52,
          valueB: 47,
          maxVal: 100,
          format: 'percent',
        },
        {
          label: 'Takedowns por 15 Min',
          valueA: 1.20,
          valueB: 0.15,
          maxVal: 5,
          format: 'decimal',
          note: 'Mullins busca mais takedowns, Carolina quase nunca tenta levar ao chao',
        },
        {
          label: 'Precisao de Takedown (%)',
          valueA: 40,
          valueB: 25,
          maxVal: 100,
          format: 'percent',
        },
        {
          label: 'Defesa de Takedown (%)',
          valueA: 65,
          valueB: 76,
          maxVal: 100,
          format: 'percent',
          note: 'Carolina tem excelente defesa de takedown, 76%, dificil de derrubar',
        },
      ],
      tale_of_tape: [
        { label: 'Idade', fighter1: '34 anos', fighter2: '32 anos', note: null },
        { label: 'Altura', fighter1: '1,70m (5\'7")', fighter2: '1,67m (5\'6")', note: null },
        { label: 'Envergadura', fighter1: '173cm (68")', fighter2: '175cm (69")', note: 'Carolina tem leve vantagem no alcance' },
        { label: 'Stance', fighter1: 'Ortodoxa', fighter2: 'Ortodoxa', note: null },
        { label: 'Academia', fighter1: 'Gym01 / Coventry, Inglaterra', fighter2: 'Tata Fight Team / Brasil', note: null },
      ],
    },

    historico_lutas: {
      fighter1: {
        nome: 'Mullins',
        recent_fights: [
          {
            date: 'Nov 2024',
            opponent: 'Klaudia Sygula',
            result: 'W',
            method: 'TKO R2 (1:20)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Primeira finalizacao no UFC, parou Sygula com strikes no segundo round. Resposta forte apos derrota.',
          },
          {
            date: 'Abr 2024',
            opponent: 'Nora Cornolle',
            result: 'L',
            method: 'TKO R2 (3:06)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Parada no segundo round por strikes, exposta no striking contra francesa mais tecnica.',
          },
          {
            date: 'Out 2023',
            opponent: 'Irina Alekseeva',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Estreia no UFC com vitoria solida por pontos em 3 rounds, controle tatico.',
          },
          {
            date: 'Mai 2023',
            opponent: 'Daria Zhelezniakova',
            result: 'L',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Derrota por pontos antes de entrar no UFC, combate competitivo mas insuficiente.',
          },
          {
            date: 'Dez 2022',
            opponent: 'Mariam Torchinava',
            result: 'W',
            method: 'KO R1',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Nocaute no primeiro round no circuito europeu, mostrando poder surpreendente.',
          },
        ],
      },
      fighter2: {
        nome: 'Carolina',
        recent_fights: [
          {
            date: 'Set 2025',
            opponent: 'Michelle Montague',
            result: 'L',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Derrota com deducao de ponto por upkick ilegal. Primeira luta no peso galo, adaptacao complicada.',
          },
          {
            date: 'Jul 2024',
            opponent: 'Lucie Pudilova',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 3,
            quality_label: 'Bom',
            note: 'Vitoria solida contra veterana da divisao, dominou com striking tecnico por 3 rounds.',
          },
          {
            date: 'Fev 2024',
            opponent: 'Julija Stoliarenko',
            result: 'W',
            method: 'TKO R3',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'TKO no terceiro round, finalizacao por strikes apos dominar a luta inteira.',
          },
          {
            date: 'Set 2023',
            opponent: 'Bruna Brasil',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Vitoria por pontos em luta competitiva, manteve sequencia positiva.',
          },
          {
            date: 'Jun 2023',
            opponent: 'Norma Dumont',
            result: 'L',
            method: 'Decisao Unanime',
            opponent_rank: '#12 FW',
            quality_score: 4,
            quality_label: 'Muito Bom',
            note: 'Derrota contra ranqueada, nivel de oposicao muito acima. Norma dominou por 3 rounds.',
          },
        ],
      },
    },

    perfil_habilidades: {
      skills: [
        {
          label: 'Striking em Pe',
          valueA: 58,
          valueB: 72,
          labelA: 'Bom',
          labelB: 'Bom',
          advantage: 'fighter2',
          advantage_note: 'Carolina tem faixa preta de Muay Thai e volume de 4.65 SLpM com 50% de precisao. Mullins e competente mas menos tecnica.',
        },
        {
          label: 'Poder de Finalizacao',
          valueA: 58,
          valueB: 60,
          labelA: 'Bom',
          labelB: 'Bom',
          advantage: 'even',
          advantage_note: 'Ambas tem TKOs recentes, Mullins parou Sygula e Carolina parou Stoliarenko. Poder similar na divisao.',
        },
        {
          label: 'Wrestling e Grappling',
          valueA: 55,
          valueB: 52,
          labelA: 'Bom',
          labelB: 'Medio',
          advantage: 'even',
          advantage_note: 'Mullins busca mais takedowns (1.20/15min) mas Carolina defende 76%. Jiu-jitsu competitivo para ambas.',
        },
        {
          label: 'Defesa Geral',
          valueA: 55,
          valueB: 58,
          labelA: 'Bom',
          labelB: 'Bom',
          advantage: 'even',
          advantage_note: 'Mullins foi parada por Cornolle e Carolina perdeu por decisao. Ambas tem vulnerabilidades mas nenhuma e fragil.',
        },
        {
          label: 'Cardio e Ritmo',
          valueA: 60,
          valueB: 68,
          labelA: 'Bom',
          labelB: 'Bom',
          advantage: 'fighter2',
          advantage_note: 'Carolina tem 10 lutas no UFC e ja lutou 5 rounds. Experiencia em manter ritmo alto por toda a luta.',
        },
        {
          label: 'Experiencia no UFC',
          valueA: 45,
          valueB: 78,
          labelA: 'Medio',
          labelB: 'Muito Bom',
          advantage: 'fighter2',
          advantage_note: 'Carolina tem 10 lutas no UFC (6V-4D) incluindo lutas contra ranqueadas. Mullins tem 3 lutas (2V-1D). Diferenca enorme.',
        },
      ],
      insight: 'Carolina e a lutadora mais experiente e completa, com faixa preta de Muay Thai, 10 lutas no UFC e volume de strikes superior. Mullins traz coragem e poder de finalizacao, mas falta experiencia no alto nivel. A brasileira vem de derrota e precisa da vitoria para manter seu lugar na divisao, o que pode gerar urgencia extra.',
    },

    distribuicao_vitorias: {
      fighter1: {
        nome: 'Mullins',
        ko_tko: { count: 4, percent: 57 },
        submission: { count: 0, percent: 0 },
        decision: { count: 3, percent: 43 },
        total_wins: 7,
      },
      fighter2: {
        nome: 'Carolina',
        ko_tko: { count: 4, percent: 36 },
        submission: { count: 2, percent: 18 },
        decision: { count: 5, percent: 46 },
        total_wins: 11,
      },
      insight: 'Mullins vence 57% por KO/TKO e 43% por decisao, perfil direto sem finalizacoes. Carolina e mais equilibrada com 46% por decisao, 36% por KO e 18% por finalizacao. Carolina tem mais ferramentas para buscar a vitoria de diferentes formas, enquanto Mullins depende mais do poder nos golpes.',
    },

    previsao_final: {
      winner_name: 'Carolina',
      winner_side: 'fighter2',
      predicted_method: 'Decisao Unanime',
      confidence_score: 6,
      confidence_label: 'MEDIA',
      explanation: 'Luana Carolina tem vantagem significativa em experiencia (10 lutas no UFC vs 3), volume de strikes (4.65 vs 3.80 SLpM) e versatilidade. Sua faixa preta de Muay Thai deve dar vantagem tecnica na trocacao contra Mullins, que foi parada por strikes por Cornolle. Carolina vem de derrota e tem motivacao extra, enquanto Mullins viaja para Londres com menos experiencia no Octagon. Porem, Mullins luta em casa e mostrou capacidade de finalizacao ao parar Sygula. Se a inglesa conectar no tempo certo, pode surpreender.',
      x_factor: {
        title: 'A experiencia de Carolina no UFC',
        description: 'Com 10 lutas no Octagon contra apenas 3 de Mullins, Carolina sabe lidar com a pressao, o ritmo e os juizes do UFC. Essa maturidade competitiva e insubstituivel e deve aparecer nos momentos decisivos da luta.',
      },
      upset_alert: {
        title: 'Mullins em casa com poder de finalizacao',
        description: 'Mullins parou Sygula com strikes no R2 e tem 57% de vitorias por KO/TKO. A torcida da O2 Arena vai empurrar a inglesa e, se Carolina mostrar as mesmas lacunas defensivas que apareceram contra Montague, Mullins pode capitalizar.',
      },
      probabilities: {
        fighter1: { nome: 'Mullins', percent: 40 },
        fighter2: { nome: 'Carolina', percent: 58 },
        draw: 2,
      },
      value_picks: undefined,
    },
  },
};

export default function Page() {
  return <PrelimsAnalysisView analise={analise} />;
}
