'use client';

import { Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { PrelimsAnalysisView } from '@/components/analise/PrelimsAnalysisView';
import type { PrelimsAnalise } from '@/types/analise';
import type { Lang } from '@/lib/i18n-labels';

const analisePT: PrelimsAnalise = {
  id: 'thainara-vs-brasil',
  evento_id: null,
  slug: 'thainara-vs-brasil',
  titulo: 'Thainara vs Brasil',
  subtitulo: null,
  lutador1_id: null,
  lutador2_id: null,
  artigo_conteudo: '',
  tactical_breakdown: {
    stats: [],
    radarData: [],
    taleOfTape: {
      fighter1: { altura: '', envergadura: '', idade: 0, academia: '' },
      fighter2: { altura: '', envergadura: '', idade: 0, academia: '' },
    },
    pathsToVictory: { fighter1: [], fighter2: [] },
    dangerZones: [],
  },
  fight_prediction: {
    predictedWinner: 'fighter1',
    predictedMethod: 'Decisao Unanime',
    confidence: 'MEDIA-ALTA',
    fighter1Scenarios: [],
    fighter2Scenarios: [],
    keyFactors: [],
    xFactor: { title: '', description: '' },
  },
  fighter1_info: {
    nome: 'Alexia Thainara',
    record: '13-1-0',
    ultimasLutas: [],
  },
  fighter2_info: {
    nome: 'Bruna Brasil',
    record: '11-6-1',
    ultimasLutas: [],
  },
  evento_nome: 'UFC Fight Night: Adesanya vs Pyfer',
  evento_data: '28 de Marco, 2026',
  evento_local: 'Climate Pledge Arena, Seattle, Washington',
  categoria_peso: 'Peso Palha Feminino (115 lbs)',
  num_rounds: 3,
  is_titulo: false,
  broadcast: null,
  status: 'published',
  analysis_type: 'prelims',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),

  prelims_analysis: {
    hero: {
      evento_nome: 'UFC Fight Night: Adesanya vs Pyfer',
      evento_data: '28 de Marco, 2026',
      categoria_peso: 'Peso Palha Feminino (115 lbs)',
      num_rounds: 3,
      is_titulo: false,
      fighter1: {
        nome: 'Thainara',
        record: '13-1-0',
        ranking: '#13 WSW',
      },
      fighter2: {
        nome: 'Brasil',
        record: '11-6-1',
        ranking: undefined,
      },
    },

    comparacao_estatistica: {
      stats: [
        {
          label: 'Sig. Strikes por Minuto',
          valueA: 5.73,
          valueB: 2.66,
          maxVal: 8,
          format: 'decimal',
          note: 'Thainara tem volume massivo, mais que o dobro de Brasil. 5.73 SLpM e numero de elite na divisao.',
        },
        {
          label: 'Precisao de Strikes (%)',
          valueA: 40,
          valueB: 56,
          maxVal: 100,
          format: 'percent',
          note: 'Brasil e mais cirurgica com 56%, mas lanca menos. Thainara compensa a menor precisao com volume absurdo.',
        },
        {
          label: 'Strikes Absorvidos/Min',
          valueA: 2.82,
          valueB: 2.66,
          maxVal: 6,
          format: 'decimal',
          reverseWinner: true,
          note: 'Numeros muito proximos na absorcao de dano. Ambas ficam abaixo de 3 strikes absorvidos por minuto.',
        },
        {
          label: 'Defesa de Strikes (%)',
          valueA: 70,
          valueB: 52,
          maxVal: 100,
          format: 'percent',
          note: 'Thainara defende 70% dos golpes, numero excepcional. Brasil absorve quase metade do que lancam nela.',
        },
        {
          label: 'Takedowns por 15 Min',
          valueA: 3.32,
          valueB: 1.46,
          maxVal: 5,
          format: 'decimal',
          note: 'Thainara busca mais que o dobro de takedowns, reflexo do seu jiu-jitsu faixa preta.',
        },
        {
          label: 'Precisao de Takedown (%)',
          valueA: 85,
          valueB: 64,
          maxVal: 100,
          format: 'percent',
          note: 'Thainara converte 85% dos takedowns, numero absurdo. Quando ela decide derrubar, derruba.',
        },
        {
          label: 'Defesa de Takedown (%)',
          valueA: 85,
          valueB: 53,
          maxVal: 100,
          format: 'percent',
          note: 'Mais uma vantagem massiva de Thainara: 85% vs 53%. Brasil e vulneravel a quedas.',
        },
      ],
      tale_of_tape: [
        { label: 'Idade', fighter1: '30 anos', fighter2: '32 anos', note: null },
        { label: 'Altura', fighter1: '1,63m (5\'4")', fighter2: '1,68m (5\'6")', note: 'Brasil tem 5cm a mais de altura' },
        { label: 'Envergadura', fighter1: '170cm (67")', fighter2: '166cm (65.5")', note: 'Thainara tem leve vantagem de alcance apesar de ser mais baixa' },
        { label: 'Stance', fighter1: 'Ortodoxa', fighter2: 'Ortodoxa', note: null },
        { label: 'Academia', fighter1: 'Brasil', fighter2: 'The Fighting Nerds / Brasil', note: null },
      ],
    },

    historico_lutas: {
      fighter1: {
        nome: 'Thainara',
        recent_fights: [
          {
            date: 'Set 2025',
            opponent: 'Loma Lookboonmee',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Dominou com 110 strikes, 5 takedowns e mais de 10 minutos de controle. Vitoria convincente na Australia.',
          },
          {
            date: 'Mar 2025',
            opponent: 'Molly McCann',
            result: 'W',
            method: 'Sub R1 (4:32)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Estreia no UFC com finalizacao por mata-leao no primeiro round. Ganhou bonus de Performance da Noite ($50k).',
          },
          {
            date: 'Set 2024',
            opponent: 'Rose Conceicao',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Vitoria no Contender Series que garantiu seu contrato com o UFC. Venceu ex-parceira de treino.',
          },
          {
            date: 'Nov 2019',
            opponent: 'Bruna Brasil',
            result: 'L',
            method: 'Sub R3 (0:33)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Unica derrota profissional. Guilhotina de Brasil aos 33 segundos do terceiro round no Thunder Fight 20.',
          },
        ],
      },
      fighter2: {
        nome: 'Brasil',
        recent_fights: [
          {
            date: 'Fev 2026',
            opponent: 'Ketlen Souza',
            result: 'L',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Derrota por decisao unanime (28-29, 28-29, 28-29). Retorno rapido em menos de 2 meses para essa luta.',
          },
          {
            date: 'Ago 2025',
            opponent: 'Shi Ming',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Vitoria no Road to UFC em Shanghai. Oponente de nivel abaixo do UFC regular.',
          },
          {
            date: 'Fev 2025',
            opponent: 'Wang Cong',
            result: 'L',
            method: 'Decisao Unanime',
            opponent_rank: '#15 WSW',
            quality_score: 3,
            quality_label: 'Bom',
            note: 'Subiu para short notice no UFC 312 e perdeu por decisao unanime (27-30, 27-30, 27-30). Dominada completamente.',
          },
          {
            date: 'Jul 2024',
            opponent: 'Molly McCann',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Vitoria solida por decisao unanime (30-27, 30-27, 29-28) no UFC 304 em Manchester.',
          },
          {
            date: 'Fev 2024',
            opponent: 'Loma Lookboonmee',
            result: 'L',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Perdeu por decisao unanime (28-29, 28-29, 28-29). Luta competitiva mas insuficiente nos rounds finais.',
          },
        ],
      },
    },

    perfil_habilidades: {
      skills: [
        {
          label: 'Striking em Pe',
          valueA: 72,
          valueB: 60,
          labelA: 'Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Thainara tem volume absurdo de 5.73 SLpM e 70% de defesa. Brasil e mais precisa (56%) mas produz muito menos volume (2.66 SLpM).',
        },
        {
          label: 'Jiu-Jitsu e Submissoes',
          valueA: 88,
          valueB: 55,
          labelA: 'Muito Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Thainara e faixa preta com 8 vitorias por finalizacao (5 mata-leoes, 3 armbars). Brasil tem faixa marrom e 2 subs na carreira.',
        },
        {
          label: 'Wrestling e Takedowns',
          valueA: 82,
          valueB: 52,
          labelA: 'Muito Bom',
          labelB: 'Medio',
          advantage: 'fighter1',
          advantage_note: 'Thainara converte 85% dos takedowns e defende 85%. Brasil converte 64% e defende apenas 53%. Abismo tecnico aqui.',
        },
        {
          label: 'Defesa Geral',
          valueA: 78,
          valueB: 52,
          labelA: 'Muito Bom',
          labelB: 'Medio',
          advantage: 'fighter1',
          advantage_note: 'Thainara defende 70% dos strikes e 85% dos takedowns. Brasil fica em 52% e 53%. Diferenca significativa em todas as areas defensivas.',
        },
        {
          label: 'Cardio e Ritmo',
          valueA: 72,
          valueB: 62,
          labelA: 'Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Thainara manteve volume alto por 3 rounds contra Lookboonmee com 10 minutos de controle. Brasil tende a cair de producao nos rounds finais.',
        },
        {
          label: 'Experiencia no UFC',
          valueA: 48,
          valueB: 65,
          labelA: 'Medio',
          labelB: 'Bom',
          advantage: 'fighter2',
          advantage_note: 'Brasil tem 8 lutas no UFC contra apenas 2 de Thainara. Porem, a qualidade das performances de Thainara compensa parcialmente a diferenca.',
        },
      ],
      insight: 'Thainara domina em praticamente todas as categorias tecnicas: volume de strikes, jiu-jitsu, wrestling e defesa. Brasil tem vantagem em experiencia no UFC com 8 lutas, mas seus numeros em todas as metricas sao inferiores. A unica vantagem concreta de Brasil e a historia entre as duas, ja que finalizou Thainara em 2019. Mas a Thainara de 2026 e uma lutadora completamente diferente daquela de 7 anos atras.',
    },

    distribuicao_vitorias: {
      fighter1: {
        nome: 'Thainara',
        ko_tko: { count: 0, percent: 0 },
        submission: { count: 8, percent: 62 },
        decision: { count: 5, percent: 38 },
        total_wins: 13,
      },
      fighter2: {
        nome: 'Brasil',
        ko_tko: { count: 3, percent: 27 },
        submission: { count: 2, percent: 18 },
        decision: { count: 6, percent: 55 },
        total_wins: 11,
      },
      insight: 'Perfis completamente diferentes. Thainara e uma finalizadora nata com 62% das vitorias por submissao (8 subs, incluindo 5 mata-leoes e 3 armbars) e zero nocautes. Brasil e mais diversificada com 3 KOs, 2 finalizacoes e 6 decisoes, mas sem um caminho dominante. Quando Thainara leva a luta pro chao, fecha. Brasil precisa manter a distancia e evitar o clinch a todo custo.',
    },

    previsao_final: {
      winner_name: 'Thainara',
      winner_side: 'fighter1',
      predicted_method: 'Submissao ou Decisao Unanime',
      confidence_score: 7,
      confidence_label: 'MEDIA-ALTA',
      explanation: 'Thainara evoluiu demais desde a derrota para Brasil em 2019. Em 11 lutas consecutivas desde aquela guilhotina, nao perdeu. Seus numeros no UFC sao impressionantes: 5.73 SLpM, 85% de precisao em takedowns, 85% de defesa de takedowns e 70% de defesa de strikes. Brasil, por outro lado, vem de derrota para Ketlen Souza e esta lutando com turnaround de menos de 2 meses. Os numeros de Brasil em defesa de takedown (53%) sao preocupantes contra alguem que converte 85%. Se Thainara decidir derrubar, vai derrubar, e no chao ela e faixa preta com 8 finalizacoes na carreira.',
      x_factor: {
        title: 'A vinganca pessoal de Thainara',
        description: 'Brasil e a unica pessoa que derrotou Thainara profissionalmente. Essa luta carrega um peso emocional enorme. Thainara trabalhou em construcao civil antes de chegar ao UFC e agora tem a chance de apagar a unica mancha do seu cartel contra a mesma pessoa, no maior palco do esporte. Motivacao nao vai faltar.',
      },
      upset_alert: {
        title: 'A guilhotina ainda mora na memoria',
        description: 'Brasil ja provou que sabe finalizar Thainara. Se conseguir encaixar o clinch e buscar a guilhotina novamente, pode repetir a historia. Thainara vai ter que administrar a ansiedade de revanche sem se expor demais nas trocas de pe, onde Brasil tem mais precisao (56% vs 40%).',
      },
      probabilities: {
        fighter1: { nome: 'Thainara', percent: 68 },
        fighter2: { nome: 'Brasil', percent: 30 },
        draw: 2,
      },
      value_picks: undefined,
    },
  },
};

const analiseEN: PrelimsAnalise = {
  ...analisePT,
  evento_data: 'March 28, 2026',
  evento_local: 'Climate Pledge Arena, Seattle, Washington',
  categoria_peso: "Women's Strawweight (115 lbs)",
  fight_prediction: {
    ...analisePT.fight_prediction,
    predictedMethod: 'Submission or Unanimous Decision',
    confidence: 'MEDIUM-HIGH',
  },
  prelims_analysis: {
    hero: {
      ...analisePT.prelims_analysis.hero,
      evento_data: 'March 28, 2026',
      categoria_peso: "Women's Strawweight (115 lbs)",
    },
    comparacao_estatistica: {
      stats: [
        {
          label: 'Sig. Strikes Per Minute',
          valueA: 5.73,
          valueB: 2.66,
          maxVal: 8,
          format: 'decimal',
          note: 'Thainara has massive volume, more than double Brasil. 5.73 SLpM is elite for the division.',
        },
        {
          label: 'Striking Accuracy (%)',
          valueA: 40,
          valueB: 56,
          maxVal: 100,
          format: 'percent',
          note: 'Brasil is more surgical at 56%, but throws far less. Thainara compensates lower accuracy with absurd volume.',
        },
        {
          label: 'Strikes Absorbed/Min',
          valueA: 2.82,
          valueB: 2.66,
          maxVal: 6,
          format: 'decimal',
          reverseWinner: true,
          note: 'Very close absorption numbers. Both stay below 3 significant strikes absorbed per minute.',
        },
        {
          label: 'Strike Defense (%)',
          valueA: 70,
          valueB: 52,
          maxVal: 100,
          format: 'percent',
          note: 'Thainara defends 70% of strikes, an exceptional number. Brasil absorbs nearly half of what is thrown at her.',
        },
        {
          label: 'Takedowns Per 15 Min',
          valueA: 3.32,
          valueB: 1.46,
          maxVal: 5,
          format: 'decimal',
          note: 'Thainara attempts more than double the takedowns, reflecting her black belt BJJ.',
        },
        {
          label: 'Takedown Accuracy (%)',
          valueA: 85,
          valueB: 64,
          maxVal: 100,
          format: 'percent',
          note: 'Thainara converts 85% of takedowns, an absurd number. When she decides to take it down, she does.',
        },
        {
          label: 'Takedown Defense (%)',
          valueA: 85,
          valueB: 53,
          maxVal: 100,
          format: 'percent',
          note: 'Another massive Thainara advantage: 85% vs 53%. Brasil is vulnerable to takedowns.',
        },
      ],
      tale_of_tape: [
        { label: 'Age', fighter1: '30 years old', fighter2: '32 years old', note: null },
        { label: 'Height', fighter1: '5\'4" (1.63m)', fighter2: '5\'6" (1.68m)', note: 'Brasil has 2 inches of height advantage' },
        { label: 'Reach', fighter1: '67" (170cm)', fighter2: '65.5" (166cm)', note: 'Thainara has a slight reach advantage despite being shorter' },
        { label: 'Stance', fighter1: 'Orthodox', fighter2: 'Orthodox', note: null },
        { label: 'Gym', fighter1: 'Brazil', fighter2: 'The Fighting Nerds / Brazil', note: null },
      ],
    },
    historico_lutas: {
      fighter1: {
        nome: 'Thainara',
        recent_fights: [
          {
            date: 'Sep 2025',
            opponent: 'Loma Lookboonmee',
            result: 'W',
            method: 'Unanimous Decision',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Average',
            note: 'Dominated with 110 strikes, 5 takedowns and over 10 minutes of control time. Convincing win in Australia.',
          },
          {
            date: 'Mar 2025',
            opponent: 'Molly McCann',
            result: 'W',
            method: 'Sub R1 (4:32)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Average',
            note: 'UFC debut with a rear-naked choke in round 1. Earned $50k Performance of the Night bonus.',
          },
          {
            date: 'Sep 2024',
            opponent: 'Rose Conceicao',
            result: 'W',
            method: 'Unanimous Decision',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Poor',
            note: 'Contender Series win that earned her UFC contract. Beat former training partner.',
          },
          {
            date: 'Nov 2019',
            opponent: 'Bruna Brasil',
            result: 'L',
            method: 'Sub R3 (0:33)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Average',
            note: 'Only professional loss. Brasil guillotine choke at 0:33 of round 3 at Thunder Fight 20.',
          },
        ],
      },
      fighter2: {
        nome: 'Brasil',
        recent_fights: [
          {
            date: 'Feb 2026',
            opponent: 'Ketlen Souza',
            result: 'L',
            method: 'Unanimous Decision',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Average',
            note: 'Unanimous decision loss (28-29, 28-29, 28-29). Quick turnaround, fighting again in less than 2 months.',
          },
          {
            date: 'Aug 2025',
            opponent: 'Shi Ming',
            result: 'W',
            method: 'Unanimous Decision',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Poor',
            note: 'Road to UFC win in Shanghai. Below-regular UFC level opponent.',
          },
          {
            date: 'Feb 2025',
            opponent: 'Wang Cong',
            result: 'L',
            method: 'Unanimous Decision',
            opponent_rank: '#15 WSW',
            quality_score: 3,
            quality_label: 'Good',
            note: 'Stepped up on short notice at UFC 312 and lost by unanimous decision (27-30, 27-30, 27-30). Completely dominated.',
          },
          {
            date: 'Jul 2024',
            opponent: 'Molly McCann',
            result: 'W',
            method: 'Unanimous Decision',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Average',
            note: 'Solid unanimous decision win (30-27, 30-27, 29-28) at UFC 304 in Manchester.',
          },
          {
            date: 'Feb 2024',
            opponent: 'Loma Lookboonmee',
            result: 'L',
            method: 'Unanimous Decision',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Average',
            note: 'Unanimous decision loss (28-29, 28-29, 28-29). Competitive fight but insufficient in later rounds.',
          },
        ],
      },
    },
    perfil_habilidades: {
      skills: [
        {
          label: 'Stand-up Striking',
          valueA: 72,
          valueB: 60,
          labelA: 'Good',
          labelB: 'Good',
          advantage: 'fighter1',
          advantage_note: 'Thainara has absurd volume at 5.73 SLpM with 70% defense. Brasil is more accurate (56%) but produces far less volume (2.66 SLpM).',
        },
        {
          label: 'Jiu-Jitsu & Submissions',
          valueA: 88,
          valueB: 55,
          labelA: 'Very Good',
          labelB: 'Good',
          advantage: 'fighter1',
          advantage_note: 'Thainara is a black belt with 8 submission wins (5 RNCs, 3 armbars). Brasil has a brown belt and 2 career subs.',
        },
        {
          label: 'Wrestling & Takedowns',
          valueA: 82,
          valueB: 52,
          labelA: 'Very Good',
          labelB: 'Average',
          advantage: 'fighter1',
          advantage_note: 'Thainara converts 85% of takedowns and defends 85%. Brasil converts 64% and defends only 53%. Massive gap.',
        },
        {
          label: 'Overall Defense',
          valueA: 78,
          valueB: 52,
          labelA: 'Very Good',
          labelB: 'Average',
          advantage: 'fighter1',
          advantage_note: 'Thainara defends 70% of strikes and 85% of takedowns. Brasil sits at 52% and 53%. Significant gap across all defensive areas.',
        },
        {
          label: 'Cardio & Pace',
          valueA: 72,
          valueB: 62,
          labelA: 'Good',
          labelB: 'Good',
          advantage: 'fighter1',
          advantage_note: 'Thainara maintained high volume through 3 rounds vs Lookboonmee with 10 min control time. Brasil tends to drop off in later rounds.',
        },
        {
          label: 'UFC Experience',
          valueA: 48,
          valueB: 65,
          labelA: 'Average',
          labelB: 'Good',
          advantage: 'fighter2',
          advantage_note: 'Brasil has 8 UFC fights vs only 2 for Thainara. However, the quality of Thainara\'s performances partially offsets the gap.',
        },
      ],
      insight: 'Thainara dominates in virtually every technical category: strike volume, jiu-jitsu, wrestling, and defense. Brasil has the experience edge with 8 UFC fights, but her numbers across all metrics are inferior. Brasil\'s only concrete advantage is history, having submitted Thainara in 2019. But the 2026 Thainara is a completely different fighter from 7 years ago.',
    },
    distribuicao_vitorias: {
      fighter1: {
        nome: 'Thainara',
        ko_tko: { count: 0, percent: 0 },
        submission: { count: 8, percent: 62 },
        decision: { count: 5, percent: 38 },
        total_wins: 13,
      },
      fighter2: {
        nome: 'Brasil',
        ko_tko: { count: 3, percent: 27 },
        submission: { count: 2, percent: 18 },
        decision: { count: 6, percent: 55 },
        total_wins: 11,
      },
      insight: 'Completely different profiles. Thainara is a natural finisher with 62% wins by submission (8 subs, including 5 RNCs and 3 armbars) and zero knockouts. Brasil is more diversified with 3 KOs, 2 submissions, and 6 decisions, but no dominant path. When Thainara takes it to the ground, she finishes. Brasil needs to maintain distance and avoid the clinch at all costs.',
    },
    previsao_final: {
      winner_name: 'Thainara',
      winner_side: 'fighter1',
      predicted_method: 'Submission or Unanimous Decision',
      confidence_score: 7,
      confidence_label: 'MEDIUM-HIGH',
      explanation: 'Thainara has evolved tremendously since her loss to Brasil in 2019. In 11 consecutive fights since that guillotine, she hasn\'t lost. Her UFC numbers are impressive: 5.73 SLpM, 85% takedown accuracy, 85% takedown defense, and 70% strike defense. Brasil, on the other hand, is coming off a loss to Ketlen Souza with a turnaround of less than 2 months. Brasil\'s 53% takedown defense is concerning against someone who converts 85%. If Thainara decides to take it down, she will, and on the ground she\'s a black belt with 8 career submissions.',
      x_factor: {
        title: 'Thainara\'s personal revenge',
        description: 'Brasil is the only person to have defeated Thainara professionally. This fight carries enormous emotional weight. Thainara worked in construction before making it to the UFC and now has the chance to erase the only blemish on her record against the same person, on the biggest stage in the sport.',
      },
      upset_alert: {
        title: 'The guillotine still lives in memory',
        description: 'Brasil has already proven she can submit Thainara. If she can lock in the clinch and hunt for the guillotine again, she could repeat history. Thainara will need to manage her rematch anxiety without over-exposing herself in the standup, where Brasil has better accuracy (56% vs 40%).',
      },
      probabilities: {
        fighter1: { nome: 'Thainara', percent: 68 },
        fighter2: { nome: 'Brasil', percent: 30 },
        draw: 2,
      },
      value_picks: undefined,
    },
  },
};

function PageContent() {
  const searchParams = useSearchParams();
  const lang = (searchParams.get('lang') === 'en' ? 'en' : 'pt') as Lang;
  const analise = lang === 'en' ? analiseEN : analisePT;
  return <PrelimsAnalysisView analise={analise} lang={lang} />;
}

export default function Page() {
  return <Suspense><PageContent /></Suspense>;
}
