import { RecapView } from '@/components/recap/RecapView';
import { enrichRecapWithPhotos } from '@/lib/enrich-recap-photos';
import type { RecapData } from '@/types/recap';

export const dynamic = 'force-dynamic';

const recapData: RecapData = {
  evento_nome: 'UFC Fight Night: Emmett vs Vallejos',
  evento_data: 'March 14, 2026',
  evento_local: 'Meta APEX, Las Vegas, Nevada',
  evento_numero: 'UFC Vegas 114 / UFC Fight Night 269',

  total_fights: 14,
  predictions_correct: 10,
  methods_correct: 4,

  main_card: [
    {
      slug: 'emmett-vs-vallejos',
      fighter1: { nome: 'Josh Emmett', record: '19-7-0' },
      fighter2: { nome: 'Kevin Vallejos', record: '18-1-0' },
      categoria_peso: 'Featherweight (145 lbs)',
      num_rounds: 5,
      is_main_event: true,
      predicted_winner: 'Kevin Vallejos',
      predicted_method: 'TKO R2-R3 or Unanimous Decision',
      confidence_label: 'MEDIUM-HIGH',
      actual_winner: 'Kevin Vallejos',
      actual_method: 'TKO (Punches)',
      actual_round: 1,
      actual_time: '3:33',
      prediction_correct: true,
      method_correct: true,
      bonus: 'POTN',
    },
    {
      slug: 'lemos-vs-robertson',
      fighter1: { nome: 'Amanda Lemos', record: '15-6-1' },
      fighter2: { nome: 'Gillian Robertson', record: '17-8-0' },
      categoria_peso: "Women's Strawweight (115 lbs)",
      num_rounds: 3,
      predicted_winner: 'Gillian Robertson',
      predicted_method: 'Unanimous Decision',
      confidence_label: 'MEDIUM',
      actual_winner: 'Gillian Robertson',
      actual_method: 'Unanimous Decision (29-28, 29-28, 29-28)',
      prediction_correct: true,
      method_correct: true,
    },
    {
      slug: 'fili-vs-delgado',
      fighter1: { nome: 'Andre Fili', record: '25-13-0' },
      fighter2: { nome: 'Jose Miguel Delgado', record: '11-2-0' },
      categoria_peso: 'Featherweight (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Jose Miguel Delgado',
      predicted_method: 'TKO R1 or R2',
      confidence_label: 'MEDIUM',
      actual_winner: 'Jose Miguel Delgado',
      actual_method: 'Split Decision (29-28, 28-29, 29-28)',
      prediction_correct: true,
      method_correct: false,
    },
    {
      slug: 'rahiki-vs-hardwick',
      fighter1: { nome: 'Marwan Rahiki', record: '8-0-0' },
      fighter2: { nome: 'Harry Hardwick', record: '13-5-1' },
      categoria_peso: 'Featherweight (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Marwan Rahiki',
      predicted_method: 'KO/TKO in first two rounds',
      confidence_label: 'MEDIUM',
      actual_winner: 'Marwan Rahiki',
      actual_method: 'TKO (Injury)',
      actual_round: 2,
      actual_time: '5:00',
      prediction_correct: true,
      method_correct: false,
      bonus: 'FOTN',
    },
    {
      slug: 'cutelaba-vs-sy',
      fighter1: { nome: 'Ion Cutelaba', record: '20-11-1' },
      fighter2: { nome: 'Oumar Sy', record: '12-2-0' },
      categoria_peso: 'Light Heavyweight (205 lbs)',
      num_rounds: 3,
      predicted_winner: 'Oumar Sy',
      predicted_method: 'TKO R2 or Unanimous Decision',
      confidence_label: 'MEDIUM',
      actual_winner: 'Ion Cutelaba',
      actual_method: 'Submission (Mounted Guillotine)',
      actual_round: 1,
      actual_time: '4:24',
      prediction_correct: false,
      method_correct: false,
    },
    {
      slug: 'johnson-vs-silva',
      fighter1: { nome: 'Charles Johnson', record: '19-8-0' },
      fighter2: { nome: 'Bruno Silva', record: '15-8-2' },
      categoria_peso: 'Flyweight (125 lbs)',
      num_rounds: 3,
      predicted_winner: 'Charles Johnson',
      predicted_method: 'Unanimous Decision',
      confidence_label: 'MEDIUM',
      actual_winner: 'Charles Johnson',
      actual_method: 'Split Decision (30-27, 29-28, 29-28)',
      prediction_correct: true,
      method_correct: false,
    },
  ],
  prelims: [
    {
      slug: 'curtis-vs-orolbai',
      fighter1: { nome: 'Chris Curtis', record: '32-13-0, 1 NC' },
      fighter2: { nome: 'Myktybek Orolbai', record: '16-2-1' },
      categoria_peso: 'Welterweight (170 lbs)',
      num_rounds: 3,
      predicted_winner: 'Myktybek Orolbai',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIUM',
      actual_winner: 'Myktybek Orolbai',
      actual_method: 'Unanimous Decision (30-27, 30-27, 30-27)',
      prediction_correct: true,
      method_correct: false,
    },
    {
      slug: 'petrino-vs-asplund',
      fighter1: { nome: 'Vitor Petrino', record: '14-2-0' },
      fighter2: { nome: 'Steven Asplund', record: '7-2-0' },
      categoria_peso: 'Heavyweight (265 lbs)',
      num_rounds: 3,
      predicted_winner: 'Vitor Petrino',
      predicted_method: 'Submission or TKO (GNP)',
      confidence_label: 'MEDIUM-HIGH',
      actual_winner: 'Vitor Petrino',
      actual_method: 'Unanimous Decision (29-28, 29-28, 29-28)',
      prediction_correct: true,
      method_correct: false,
    },
    {
      slug: 'oki-vs-sousa',
      fighter1: { nome: 'Bolaji Oki', record: '10-4-0' },
      fighter2: { nome: 'Manoel Sousa', record: '14-1-0' },
      categoria_peso: 'Lightweight (155 lbs)',
      num_rounds: 3,
      predicted_winner: 'Manoel Sousa',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIUM-HIGH',
      actual_winner: 'Manoel Sousa',
      actual_method: 'KO (Right Hand)',
      actual_round: 3,
      actual_time: '4:12',
      prediction_correct: true,
      method_correct: true,
      bonus: 'POTN',
    },
    {
      slug: 'tavares-vs-anders',
      fighter1: { nome: 'Brad Tavares', record: '21-13-0' },
      fighter2: { nome: 'Eryk Anders', record: '18-9-0, 1 NC' },
      categoria_peso: 'Middleweight (185 lbs)',
      num_rounds: 3,
      predicted_winner: 'Brad Tavares',
      predicted_method: 'Unanimous Decision',
      confidence_label: 'MEDIUM',
      actual_winner: 'Eryk Anders',
      actual_method: 'Unanimous Decision (30-27, 29-28, 29-28)',
      prediction_correct: false,
      method_correct: false,
    },
    {
      slug: 'mesquita-vs-rendon',
      fighter1: { nome: 'Bia Mesquita', record: '7-0-0' },
      fighter2: { nome: 'Montse Rendon', record: '7-2-0' },
      categoria_peso: "Women's Bantamweight (135 lbs)",
      num_rounds: 3,
      predicted_winner: 'Bia Mesquita',
      predicted_method: 'Submission R2',
      confidence_label: 'MEDIUM-HIGH',
      actual_winner: 'Bia Mesquita',
      actual_method: 'Submission (Rear-Naked Choke)',
      actual_round: 1,
      actual_time: '2:07',
      prediction_correct: true,
      method_correct: true,
    },
    {
      slug: 'smith-vs-you',
      fighter1: { nome: 'Elijah Smith', record: '10-1-0' },
      fighter2: { nome: 'SuYoung You', record: '16-4-0, 2 NC' },
      categoria_peso: 'Bantamweight (135 lbs)',
      num_rounds: 3,
      predicted_winner: 'Elijah Smith',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIUM-HIGH',
      actual_winner: 'Elijah Smith',
      actual_method: 'Submission (Rear-Naked Choke)',
      actual_round: 2,
      actual_time: '1:04',
      prediction_correct: true,
      method_correct: false,
    },
    {
      slug: 'lacerda-vs-sosa',
      fighter1: { nome: 'Luan Lacerda', record: '13-4-0' },
      fighter2: { nome: 'Hecher Sosa', record: '15-1-0' },
      categoria_peso: 'Bantamweight (135 lbs)',
      num_rounds: 3,
      predicted_winner: 'Hecher Sosa',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIUM',
      actual_winner: 'Hecher Sosa',
      actual_method: 'Unanimous Decision (30-27, 30-27, 29-28)',
      prediction_correct: true,
      method_correct: false,
    },
    {
      slug: 'rodriguez-vs-hughes',
      fighter1: { nome: 'Piera Rodriguez', record: '12-2-0' },
      fighter2: { nome: 'Sam Hughes', record: '11-7-0' },
      categoria_peso: "Women's Strawweight (115 lbs)",
      num_rounds: 3,
      predicted_winner: 'Piera Rodriguez',
      predicted_method: 'Unanimous Decision',
      confidence_label: 'MEDIUM-HIGH',
      actual_winner: 'Piera Rodriguez',
      actual_method: 'Unanimous Decision (30-27, 30-27, 30-27)',
      prediction_correct: true,
      method_correct: true,
    },
  ],

  headlines: [
    {
      icon: 'crown',
      title: 'A Star Is Born',
      description: 'Kevin Vallejos, 24, dismantled 16-year veteran Josh Emmett in just 3:33. The largest age gap in UFC main event history (16 years, 9 months) ended with youth prevailing in devastating fashion. Vallejos moves to #9 in the featherweight rankings.',
      fighter: 'Kevin Vallejos',
      tag: 'Breakout',
    },
    {
      icon: 'skull',
      title: 'Cutelaba Refuses to Die',
      description: "Our biggest miss of the night. We picked Oumar Sy, but Ion Cutelaba had other plans. The Moldovan veteran locked in a mounted guillotine choke at 4:24 of round 1, proving that you can never count out a fighter with 30+ UFC fights of experience.",
      tag: 'Upset',
    },
    {
      icon: 'sparkles',
      title: 'Bia Mesquita: The Real Deal',
      description: "The BJJ legend turned MMA fighter needed only 2:07 to submit Montse Rendon with a rear-naked choke. At 7-0, she's the most dangerous grappler in women's bantamweight and a legitimate future title contender.",
      fighter: 'Bia Mesquita',
    },
    {
      icon: 'zap',
      title: 'Sousa Delivers KO of the Year Contender',
      description: "Manoel Sousa's perfectly timed right hand sent Bolaji Oki crashing to the canvas at 4:12 of round 3. A Performance of the Night bonus was the cherry on top of a statement victory that puts the lightweight division on notice.",
      fighter: 'Manoel Sousa',
      tag: 'Must Watch',
    },
    {
      icon: 'flame',
      title: 'War in the Cage',
      description: "Rahiki vs Hardwick earned Fight of the Night for a reason. Two featherweights went to war for nearly two full rounds until Hardwick suffered a jaw fracture. Rahiki stays undefeated at 8-0 and looked every bit a future contender.",
      fighter: 'Marwan Rahiki',
    },
    {
      icon: 'shield',
      title: 'Robertson Silences Doubters',
      description: 'Gillian Robertson extended her winning streak with a clean unanimous decision over Amanda Lemos. Moving to #5 in the strawweight rankings, Robertson is knocking on the door of a title eliminator.',
      fighter: 'Gillian Robertson',
    },
  ],

  star_of_the_night: {
    fighter: 'Kevin Vallejos',
    stat_line: 'TKO R1 (3:33) | Performance of the Night | Moves to #9 FW',
    quote: undefined,
    narrative: "At just 24 years old, Kevin 'El Chino' Vallejos stepped into his first UFC main event and delivered the kind of performance that makes the entire division take notice. He read Emmett's distance perfectly, dropped him early, and never let the veteran recover. This wasn't just a win; it was a coronation. Four victories in exactly one year, each more impressive than the last. The featherweight division has a new hunter, and nobody is safe.",
  },

  bonuses: {
    fotn: { fighter1: 'Marwan Rahiki', fighter2: 'Harry Hardwick' },
    potn: ['Kevin Vallejos', 'Manoel Sousa'],
  },

  ranking_moves: [
    { fighter: 'Kevin Vallejos', division: 'Featherweight', from: 14, to: 9, direction: 'up' },
    { fighter: 'Gillian Robertson', division: "W. Strawweight", from: 9, to: 5, direction: 'up' },
    { fighter: 'Charles Johnson', division: 'Flyweight', from: 24, to: 13, direction: 'up' },
    { fighter: 'Piera Rodriguez', division: "W. Strawweight", from: 17, to: 10, direction: 'up' },
    { fighter: 'Bia Mesquita', division: "W. Bantamweight", from: 25, to: 17, direction: 'up' },
    { fighter: 'Josh Emmett', division: 'Featherweight', from: 11, to: 16, direction: 'down' },
    { fighter: 'Amanda Lemos', division: "W. Strawweight", from: 5, to: 9, direction: 'down' },
    { fighter: 'Bruno Silva', division: 'Flyweight', from: 15, to: 22, direction: 'down' },
  ],

  whats_next: [
    {
      fighter: 'Kevin Vallejos',
      result: 'W',
      potential_opponents: ['Yair Rodriguez', 'Jean Silva', 'Pat Sabatini'],
      narrative: 'The featherweight division just got a new apex predator. Vallejos needs a top-10 opponent to validate this trajectory. A fight against Yair Rodriguez would be fireworks, while Jean Silva presents a style clash that could steal any card.',
    },
    {
      fighter: 'Gillian Robertson',
      result: 'W',
      potential_opponents: ['Yan Xiaonan', 'Denise Gomes', 'Mackenzie Dern'],
      narrative: "At #5 in the rankings, Robertson is one win away from a title eliminator. Her grappling-heavy style matches up well against most of the top 5, and the UFC should reward this streak with a marquee opponent.",
    },
    {
      fighter: 'Josh Emmett',
      result: 'L',
      potential_opponents: ['Jose Miguel Delgado', 'Sean Woodson', 'William Gomis'],
      narrative: "Three consecutive losses. The 41-year-old veteran's UFC future looks uncertain. If he continues, a fight against another aging veteran or a hungry prospect would be the litmus test for whether there's gas left in the tank.",
    },
    {
      fighter: 'Bia Mesquita',
      result: 'W',
      potential_opponents: ['Kayla Harrison', 'Sara McMann', 'Irene Aldana'],
      narrative: "The BJJ world champion turned MMA phenom is 7-0 and looking scarier with every fight. Her ground game is light years ahead of the division. A step up in competition against a ranked veteran will tell us if she's ready for the title picture.",
    },
    {
      fighter: 'Manoel Sousa',
      result: 'W',
      potential_opponents: ['Jalin Turner', 'Drew Dober', 'Renato Moicano'],
      narrative: "That right hand could knock out a bull. Sousa's KO of the Year contender finish puts him in position for a major step up. The lightweight division is stacked, but a Performance of the Night bonus opens doors.",
    },
    {
      fighter: 'Ion Cutelaba',
      result: 'W',
      potential_opponents: ['Dustin Jacoby', 'Khalil Rountree', 'Jamahal Hill'],
      narrative: "Just when you think the Hulk is done, he pulls a submission out of nowhere. The upset win over Sy proves Cutelaba still has the tools to compete at light heavyweight. A matchup with another veteran striker would be entertaining.",
    },
  ],

  model_notes: `10 out of 14 winner predictions correct (71.4%). Not bad for a card where 6 of the 14 fights were competitive enough to go to decision.

Where we nailed it: Vallejos was our strongest call, and he delivered even faster than expected. Robertson by UD was textbook. Bia Mesquita's submission dominance was exactly what we projected.

Where we missed: The Cutelaba upset was our biggest blind spot. We underestimated his veteran savvy and overvalued Sy's physical advantages. The Tavares loss was a closer call where experience should have favored our pick, but Anders showed more urgency.

Method accuracy at 4/14 (28.6%) tells a story: we were directionally right on winners but the paths to victory were less predictable. Several fights we called for finishes went to decision (Orolbai, Petrino, Sosa), while Vallejos finished even faster than projected.

Key learning: On cards heavy with prospects vs. veterans, our model tends to correctly identify which way the fight goes but overestimates finish rates. Decision victories were the dominant outcome (9 of 14 fights), suggesting we should calibrate downward on finish predictions for non-title fights at the APEX.`,

  // ═══════════════════════════════════════════════════════════
  // B2B VALUE SECTIONS
  // ═══════════════════════════════════════════════════════════

  quotable_stats: [
    {
      stat: '4-0 in 12 Months',
      context: 'Kevin Vallejos has won all four of his UFC fights within a single calendar year, each more dominant than the last. His latest: a first-round TKO of a veteran main eventer.',
      fighter: 'Kevin Vallejos',
      category: 'breakout',
      icon: 'trending',
      shareable_text: 'Kevin Vallejos: 4-0 in 12 months in the UFC. His latest victim? A veteran main eventer in under 4 minutes. The featherweight division has a new problem. #UFC #UFCVegas114',
    },
    {
      stat: '71% Winner Accuracy',
      context: 'Our prediction model correctly identified the winner in 10 of 14 fights on this card, including the main event TKO.',
      category: 'model',
      icon: 'target',
      shareable_text: '71% winner prediction accuracy across 14 fights at UFC Vegas 114. Our AI model nailed the Vallejos TKO and 9 more. #MMA #UFCPredictions',
    },
    {
      stat: '16 Years, 9 Months',
      context: 'The age gap between Josh Emmett (40) and Kevin Vallejos (24) was the largest in UFC main event history. Youth won decisively.',
      category: 'historical',
      icon: 'clock',
      shareable_text: 'RECORD BROKEN: Emmett vs Vallejos had the largest age gap in UFC main event history at 16 years, 9 months. Youth won in 3:33. #UFC #UFCVegas114',
    },
    {
      stat: '5 Finishes, $400K in Bonuses',
      context: 'The card delivered 5 finishes (2 KO/TKO, 2 submissions, 1 TKO by injury). 3 of the 5 finishes earned performance bonuses.',
      category: 'bonus',
      icon: 'award',
      shareable_text: '$400,000 in bonuses at UFC Vegas 114. Vallejos and Sousa got Performance of the Night. Rahiki vs Hardwick was Fight of the Night. #UFC',
    },
    {
      stat: '7-0 and Terrifying',
      context: 'Bia Mesquita submitted Montse Rendon in 2:07 of round 1. The BJJ world champion is now 7-0 in MMA with five submission wins.',
      fighter: 'Bia Mesquita',
      category: 'streak',
      icon: 'flame',
      shareable_text: "Bia Mesquita: 7-0 in MMA. 5 submission wins. 2:07 to finish her last opponent. The scariest grappler in women's bantamweight. #UFC #WMMA",
    },
    {
      stat: '#9 and Rising Fast',
      context: "Vallejos jumped 5 spots to #9 in the featherweight rankings. He is the youngest fighter in the division's top 15.",
      fighter: 'Kevin Vallejos',
      category: 'breakout',
      icon: 'trending',
      shareable_text: "Kevin Vallejos: From unranked to #9 featherweight in 12 months. At 24, he's the youngest fighter in the FW top 15. #UFC",
    },
    {
      stat: '3 Consecutive Losses',
      context: "Josh Emmett has now lost three fights in a row. At 40 years old, his UFC future is uncertain.",
      fighter: 'Josh Emmett',
      category: 'streak',
      icon: 'trending',
      shareable_text: "Josh Emmett: 3 consecutive losses. 40 years old. Once a title challenger, now fighting for his roster spot. Father Time is undefeated. #UFC",
    },
    {
      stat: 'Mounted Guillotine',
      context: 'Ion Cutelaba pulled off one of the rarest submissions in UFC history to upset Oumar Sy. A mounted guillotine requires extraordinary grip strength and technique.',
      fighter: 'Ion Cutelaba',
      category: 'finish',
      icon: 'zap',
      shareable_text: "Ion Cutelaba just won by MOUNTED GUILLOTINE. One of the rarest submissions in UFC history. Everyone picked against him. He didn't care. #UFC #UFCVegas114",
    },
  ],

  narrative_threads: [
    {
      headline: 'The Coronation of Kevin Vallejos',
      slug_tag: 'RISE',
      fighters_involved: ['Kevin Vallejos', 'Josh Emmett'],
      lede: "In 3 minutes and 33 seconds, Kevin 'El Chino' Vallejos did more than win a main event. He announced himself as the future of the featherweight division with a performance so dominant it felt inevitable from the opening bell.",
      body: "The 24-year-old Argentine walked into the APEX as a significant favorite, but the manner of victory exceeded even the most bullish projections. Emmett, a former title challenger with knockout power in both hands, never found his range. Vallejos read the distance like a textbook, countered with surgical precision, and closed the show before the first round was halfway done.\n\nWhat makes Vallejos truly terrifying is the trajectory. Four fights in twelve months, each against a tougher opponent, each ending more emphatically. He's not just winning; he's getting better at a rate that should alarm everyone ranked above him.\n\nThe featherweight division just got a lot more interesting. With Ilia Topuria holding the belt and established contenders jockeying for position, Vallejos represents the new generation: younger, hungrier, and apparently immune to the pressure of the spotlight.",
      suggested_angles: [
        "Compare Vallejos' rise to other rapid featherweight climbers (Holloway, Volkanovski)",
        'Age gap analysis: when has the younger fighter dominated this convincingly in main events?',
        'Vallejos vs the featherweight top 5: stylistic breakdown of each potential matchup',
      ],
      content_type_fit: ['article', 'video', 'podcast'],
    },
    {
      headline: "The Veteran's Last Stand",
      slug_tag: 'FALL',
      fighters_involved: ['Josh Emmett', 'Andre Fili', 'Brad Tavares'],
      lede: 'UFC Vegas 114 was a brutal night for the old guard. Three veteran fighters with a combined 40+ UFC fights all lost to younger opponents, raising uncomfortable questions about the twilight of their careers.',
      body: "Josh Emmett, 40, was stopped in the first round. Andre Fili, 34, lost a split decision to a fighter with a fraction of his experience. Brad Tavares, 37, dropped a decision to Eryk Anders.\n\nThis is the brutal calculus of MMA. These fighters were, at their peaks, legitimate contenders. Emmett once knocked out Jeremy Stephens cold and challenged for the title. Fili was a staple of featherweight rankings for nearly a decade. Tavares was a top-10 middleweight for years.\n\nBut the sport doesn't care about resumes. It cares about right now. And right now, the next generation is faster, more technical, and hungry in ways that experience can't match.",
      suggested_angles: [
        'When should UFC veterans retire? A data analysis of fighters who stayed too long',
        "Counter-narrative: veterans who reinvented themselves after losing streaks",
      ],
      content_type_fit: ['article', 'podcast', 'video'],
    },
    {
      headline: "Cutelaba's Resurrection",
      slug_tag: 'UPSET',
      fighters_involved: ['Ion Cutelaba', 'Oumar Sy'],
      lede: 'Everyone wrote Ion Cutelaba off. The oddsmakers, the analysts, our own prediction model. And then the Moldovan Hulk pulled a mounted guillotine choke out of thin air.',
      body: "Cutelaba was supposed to be the stepping stone. Oumar Sy was the rising prospect, the physical specimen, the future. But Cutelaba didn't read the script.\n\nA mounted guillotine is one of the rarest finishes in MMA, requiring both technical precision and pure grip strength. For a fighter known primarily as a wild brawler, it was a shocking display of grappling acumen.\n\nThis is why MMA remains the most unpredictable sport on Earth. 30+ UFC fights of experience taught Cutelaba something that no amount of athletic talent can replace: how to find a way to win when everything says you shouldn't.",
      suggested_angles: [
        "Mounted guillotine: breaking down one of MMA's rarest submissions",
        'Data: how often do significant underdogs win in UFC light heavyweight?',
      ],
      content_type_fit: ['video', 'social', 'podcast'],
    },
    {
      headline: "The Grappling Revolution in Women's MMA",
      slug_tag: 'BREAKOUT',
      fighters_involved: ['Bia Mesquita', 'Gillian Robertson'],
      lede: "Two of the night's most impressive performances came from grapplers who have made submission fighting an art form. Mesquita's 2:07 finish and Robertson's dominant decision signal a shift in women's MMA.",
      body: "Mesquita, the multiple-time BJJ world champion, needed barely two minutes to wrap up a rear-naked choke that looked effortless. At 7-0, she's not just winning; she's making elite opponents look helpless on the ground.\n\nMeanwhile, Robertson used her grappling to neutralize Amanda Lemos across three rounds, climbing to #5 in the strawweight rankings.\n\nTogether, they represent a growing trend in women's MMA: the new wave of grapplers aren't just taking fights to the ground; they're finishing them there with a level of technical sophistication that makes you wonder if the rest of the division can keep up.",
      suggested_angles: [
        'Mesquita vs Robertson: different grappling philosophies, same dominant results',
        "Women's bantamweight and strawweight ranking implications after this event",
      ],
      content_type_fit: ['article', 'video', 'social'],
    },
  ],

  creator_kit: {
    instagram: [
      { slide_number: 1, title: 'UFC VEGAS 114 RECAP', content: 'Vallejos DESTROYS Emmett in R1\nBia Mesquita: 7-0, 2:07 SUB\nCutelaba pulls off HUGE upset\n\n71% prediction accuracy\n5 finishes, $400K in bonuses', color: 'red' },
      { slide_number: 2, title: 'STAR OF THE NIGHT', content: 'Kevin Vallejos\nTKO R1 (3:33)\n\n4-0 in 12 months\nMoves to #9 FW\nYoungest in the top 15\n\nThe featherweight division\nhas a new problem.', color: 'gold' },
      { slide_number: 3, title: 'BIGGEST UPSET', content: 'Ion Cutelaba def. Oumar Sy\nSubmission R1 (4:24)\nMounted Guillotine Choke\n\nEveryone counted him out.\nHe proved everyone wrong.', color: 'blue' },
      { slide_number: 4, title: 'BY THE NUMBERS', content: '14 fights\n5 finishes (36%)\n9 decisions\n2 KO/TKO\n2 submissions\n1 injury stoppage\n\nShortest: Mesquita 2:07', color: 'green' },
      { slide_number: 5, title: "WHAT'S NEXT", content: 'Vallejos vs Yair/Jean Silva\nRobertson vs Yan Xiaonan\nMesquita vs ranked opponent\n\nNext event:\nEvloev vs Murphy\nMarch 22', color: 'red' },
    ],
    twitter: [
      { num: '1/7', text: "UFC Vegas 114 was supposed to be a small card. Instead:\n\n- Star-making main event KO\n- Rarest submission in MMA\n- KO of the Year contender\n- FOTN war\n- 71% prediction accuracy\n\nThread:", type: 'thread_opener' },
      { num: '2/7', text: "Kevin Vallejos TKO'd Josh Emmett in 3:33. That's 4-0 in 12 months at age 24. The age gap was the LARGEST in UFC main event history.\n\nThis isn't a prospect. This is a contender.", type: 'result' },
      { num: '3/7', text: "Ion Cutelaba won by MOUNTED GUILLOTINE. Everyone picked Sy. Our model picked Sy. The oddsmakers picked Sy.\n\n30+ UFC fights of experience > physical advantages.", type: 'hot_take' },
      { num: '4/7', text: "Bia Mesquita: 7-0. Submitted Rendon in 2:07. Multiple BJJ world championships.\n\nIf she's not the scariest grappler in WMMA right now, who is?", type: 'stat' },
      { num: '5/7', text: "Manoel Sousa's right hand: KO of the Year contender. The timing. The power. Performance of the Night.", type: 'result' },
      { num: '6/7', text: 'Our model: 10/14 winners (71.4%), 4/14 methods (28.6%).\n\nWe can tell you WHO wins. HOW they win is the beautiful chaos of MMA.', type: 'stat' },
      { num: '7/7', text: "Next week: Evloev vs Murphy. Another card that looks small on paper.\n\nAfter tonight, you know better than to sleep on Fight Night cards.", type: 'thread_closer' },
    ],
    video_script: [
      { time: '0-10s', title: 'Hook', text: 'A 24-year-old just set a UFC record and demolished a veteran in under 4 minutes. UFC Vegas 114 was supposed to be a sleeper card. It was anything but.', b_roll_suggestion: 'Vallejos KO highlight in slow motion' },
      { time: '10-30s', title: 'Main Event', text: "Kevin Vallejos needed 3 minutes and 33 seconds to prove he belongs in the featherweight title conversation. Josh Emmett never found his range. The age gap was the largest in UFC main event history. This wasn't a fight. It was a statement.", b_roll_suggestion: 'Age comparison graphic, then celebration' },
      { time: '30-50s', title: 'Highlights', text: "The night's biggest surprise: Ion Cutelaba locked in a mounted guillotine on Oumar Sy. One of the rarest submissions in MMA. Meanwhile, Manoel Sousa delivered what might be the KO of the Year.", b_roll_suggestion: 'Split screen: Cutelaba sub + Sousa KO' },
      { time: '50-70s', title: 'Scorecard', text: 'Our AI prediction model went 10 for 14 on winners, 71% accuracy. We nailed Vallejos, Robertson, Mesquita, and Sousa. Biggest miss: the Cutelaba upset.', b_roll_suggestion: 'Prediction accuracy graphic' },
      { time: '70-90s', title: 'CTA', text: "Vallejos should get a top-10 opponent next. Bia Mesquita at 7-0 needs a ranked fight. Next week: Evloev vs Murphy. Subscribe for our pre-fight analysis.", b_roll_suggestion: 'Evloev vs Murphy promo graphic' },
    ],
    tiktok: [
      { hook: 'This 24-year-old just ENDED a 40-year-old veteran in under 4 minutes', body: "Kevin Vallejos vs Josh Emmett. Biggest age gap in UFC main event history. 16 YEARS apart. Vallejos dropped him, finished him, and now he's #9 in the world.", cta: 'Follow for AI-powered UFC breakdowns before every event.' },
      { hook: 'The RAREST submission in UFC just happened and nobody is talking about it', body: "Ion Cutelaba hit a MOUNTED GUILLOTINE on Oumar Sy. Everyone picked against him. Our AI picked against him. He didn't care.", cta: 'Our AI model goes 71% on fight picks. Link in bio.' },
      { hook: 'This woman is 7-0 and her fights last about 2 minutes', body: 'Bia Mesquita. BJJ world champion. Submitted her opponent in 2:07. Rear naked choke. She makes it look like rolling with beginners.', cta: 'Full recap and prediction accuracy in our latest post.' },
    ],
    podcast_talking_points: [
      { segment: 'Opening', duration_suggestion: '3-5 min', talking_points: ['14 fights, 5 finishes, $400K in bonuses. Exceeded expectations.', 'Main event over in 3:33.', 'Prediction model went 10/14 (71%).', 'Marketed as a small card, delivered more than recent PPVs.'], hot_take: 'Fight Night cards have been consistently better than PPVs in 2026.' },
      { segment: 'Main Event Deep Dive', duration_suggestion: '5-7 min', talking_points: ["Vallejos' distance management was elite.", 'Age gap record (16 years, 9 months) told the story.', 'At 24, youngest in FW top 15.', 'Emmett at 3 straight losses and 40 years old. Is it time?'], hot_take: 'Vallejos should skip the queue and fight a top-5 opponent next.' },
      { segment: 'Upset Breakdown', duration_suggestion: '3-4 min', talking_points: ['Cutelaba by mounted guillotine is the most surprising result of 2026.', "Our model gave Sy the edge everywhere. Fights aren't won on spreadsheets.", 'Veteran instinct is real and it matters.'] },
      { segment: 'Prospect Watch', duration_suggestion: '4-5 min', talking_points: ['Bia Mesquita at 7-0 is the most exciting prospect in WMMA.', 'Elijah Smith (23) submitted SuYoung You in R2.', "Sousa's KO power is legitimate.", 'Rahiki at 8-0 survived a war and earned FOTN.'], hot_take: 'Bia Mesquita will be champion within 2 years.' },
      { segment: 'Model Review', duration_suggestion: '3-4 min', talking_points: ['71% winner accuracy is above our 65% baseline.', 'Method accuracy at 28% needs work. Over-predicted finishes.', '9 of 14 fights went to decision.', 'High-confidence picks went 3-0.'], hot_take: 'AI fight prediction is getting scary good. Methods will catch up with round-by-round simulation.' },
    ],
  },

  model_autopsy: {
    overall_grade: 'B+',
    grade_context: 'Above average for a Fight Night card at the APEX',
    correct_calls: [
      { fight: 'Vallejos vs Emmett', predicted: 'Vallejos by TKO R2-R3', actual: 'Vallejos by TKO R1 (3:33)', confidence_label: 'MEDIUM-HIGH', analysis: "Our highest confidence pick delivered even faster than projected. The model correctly identified the age/speed gap and Vallejos' rising trajectory." },
      { fight: 'Robertson vs Lemos', predicted: 'Robertson by UD', actual: 'Robertson by UD (29-28 x3)', confidence_label: 'MEDIUM', analysis: "Perfect call on both winner and method. Robertson's grappling advantage was the decisive factor exactly as projected." },
      { fight: 'Mesquita vs Rendon', predicted: 'Mesquita by Sub R2', actual: 'Mesquita by RNC R1 (2:07)', confidence_label: 'MEDIUM-HIGH', analysis: "Winner and method both correct. Underestimated Mesquita's pace by one round.", error_type: 'method_miss' },
      { fight: 'Sousa vs Oki', predicted: 'Sousa by TKO R2', actual: 'Sousa by KO R3 (4:12)', confidence_label: 'MEDIUM-HIGH', analysis: "Correctly identified Sousa's power advantage. KO came one round later but the method call was essentially correct." },
    ],
    wrong_calls: [
      { fight: 'Cutelaba vs Sy', predicted: 'Sy by TKO R2 or UD', actual: 'Cutelaba by Sub R1 (4:24)', confidence_label: 'MEDIUM', analysis: "Biggest miss. Heavily favored Sy's physical advantages but completely undervalued Cutelaba's veteran fight IQ and grappling.", error_type: 'stylistic_misread' },
      { fight: 'Tavares vs Anders', predicted: 'Tavares by UD', actual: 'Anders by UD (30-27, 29-28, 29-28)', confidence_label: 'MEDIUM', analysis: "Overweighted Tavares' experience while underestimating Anders' ability to impose a pace.", error_type: 'momentum_miss' },
    ],
    patterns_learned: [
      { pattern: 'Finish rate over-projection at APEX', evidence: '7 of 10 fights predicted as finishes went to decision.', adjustment: 'Reduce finish probability by 15-20% for non-title APEX fights.' },
      { pattern: 'Veteran upset vulnerability in LHW', evidence: 'Cutelaba (30+ UFC fights) won as a significant underdog.', adjustment: "Add 'veteran resilience' factor for LHW fighters with 15+ UFC bouts." },
      { pattern: 'Grappling dominance in WMMA is under-modeled', evidence: 'Both Mesquita and Robertson won more convincingly than projected.', adjustment: "Increase weighting for elite grappling credentials in women's divisions by 10-15%." },
    ],
    confidence_calibration: {
      high_confidence_record: '3W-0L',
      medium_confidence_record: '7W-2L',
      insight: "High confidence picks were perfect at 3-0. Medium picks went 7-2. The model's confidence ranking is well-calibrated: when we're sure, we're right.",
    },
  },

  division_impacts: [
    {
      division: 'Featherweight (145 lbs)',
      fights_on_card: 4,
      title_picture_impact: "Vallejos crashing into the top 10 adds a dangerous new contender. With Topuria holding the belt, the queue for a title shot just got longer and more violent.",
      movers: [
        { fighter: 'Kevin Vallejos', result: 'W', impact_level: 'high', one_liner: 'Jumps to #9, youngest in top 15.' },
        { fighter: 'Marwan Rahiki', result: 'W', impact_level: 'medium', one_liner: '8-0 with FOTN. Needs a ranked opponent.' },
        { fighter: 'Jose Miguel Delgado', result: 'W', impact_level: 'low', one_liner: 'Split decision over Fili. Building momentum.' },
        { fighter: 'Josh Emmett', result: 'L', impact_level: 'high', one_liner: 'Falls to #16. Three straight losses at 40.' },
      ],
      narrative: 'Featherweight is going through a generational shift. The old guard is being replaced by younger, hungrier fighters.',
    },
    {
      division: "Women's Strawweight (115 lbs)",
      fights_on_card: 2,
      title_picture_impact: "Robertson at #5 is now a legitimate threat to break into title contention. One more win over a top-3 opponent could earn her a shot.",
      movers: [
        { fighter: 'Gillian Robertson', result: 'W', impact_level: 'high', one_liner: 'Climbs to #5. Grappling neutralized a dangerous striker.' },
        { fighter: 'Piera Rodriguez', result: 'W', impact_level: 'medium', one_liner: 'Rises to #10 with dominant 30-27 UD.' },
        { fighter: 'Amanda Lemos', result: 'L', impact_level: 'medium', one_liner: "Drops to #9. Striking couldn't overcome wrestling." },
      ],
      narrative: "The strawweight top 5 is being invaded by grapplers. Robertson's rise signals a tactical shift in the division.",
    },
    {
      division: "Women's Bantamweight (135 lbs)",
      fights_on_card: 1,
      title_picture_impact: "Mesquita at 7-0 with five submissions is the most whispered-about prospect in the division. Two more wins and she could be knocking on the door.",
      movers: [
        { fighter: 'Bia Mesquita', result: 'W', impact_level: 'high', one_liner: '7-0 with Sub R1. The future of this division.' },
      ],
      narrative: "Women's bantamweight has been dominated by strikers. Mesquita represents a paradigm shift with grappling so dominant that striking defense almost doesn't matter.",
    },
    {
      division: 'Light Heavyweight (205 lbs)',
      fights_on_card: 1,
      title_picture_impact: 'No significant title picture impact. Great story but limited competitive implications.',
      movers: [
        { fighter: 'Ion Cutelaba', result: 'W', impact_level: 'low', one_liner: 'Climbs 2 spots to #19. Great story, limited impact.' },
        { fighter: 'Oumar Sy', result: 'L', impact_level: 'medium', one_liner: 'Prospect hype takes a hit. Grappling defense exposed.' },
      ],
      narrative: 'This result is more cautionary tale for prospects than a division-shifting event. Sy will bounce back but needs to address his grappling.',
    },
  ],

  replay_guide: [
    { slug: 'rahiki-vs-hardwick', fighter1: 'Marwan Rahiki', fighter2: 'Harry Hardwick', rewatch_rating: 5, rewatch_label: 'Must Watch', category: 'war', why_watch: 'Fight of the Night for a reason. Non-stop action for nearly two full rounds until the injury stoppage.', key_moments: [{ timestamp: 'R1 1:30', description: 'Simultaneous power shots land', moment_type: 'exchange' }, { timestamp: 'R2 3:00', description: 'Massive right hand that Rahiki walks through', moment_type: 'exchange' }, { timestamp: 'R2 5:00', description: 'Stoppage due to jaw injury', moment_type: 'finish' }] },
    { slug: 'cutelaba-vs-sy', fighter1: 'Ion Cutelaba', fighter2: 'Oumar Sy', rewatch_rating: 5, rewatch_label: 'Must Watch', category: 'upset', why_watch: 'The upset of the night. One of the rarest submissions in UFC history. Study material for grappling nerds.', key_moments: [{ timestamp: 'R1 3:00', description: 'Cutelaba survives early pressure', moment_type: 'reversal' }, { timestamp: 'R1 4:24', description: 'Mounted guillotine choke finish', moment_type: 'finish' }] },
    { slug: 'oki-vs-sousa', fighter1: 'Bolaji Oki', fighter2: 'Manoel Sousa', rewatch_rating: 5, rewatch_label: 'Must Watch', category: 'finish', why_watch: 'KO of the Year contender. Three rounds of competitive fighting ending with a perfectly timed bomb. Performance of the Night.', key_moments: [{ timestamp: 'R3 4:12', description: "Sousa's right hand KO", moment_type: 'finish' }] },
    { slug: 'emmett-vs-vallejos', fighter1: 'Josh Emmett', fighter2: 'Kevin Vallejos', rewatch_rating: 4, rewatch_label: 'Worth It', category: 'finish', why_watch: 'Star-making first-round TKO. Short but electric. The kind of finish that defines a career.', key_moments: [{ timestamp: 'R1 2:45', description: 'First knockdown', moment_type: 'knockdown' }, { timestamp: 'R1 3:33', description: 'TKO finish', moment_type: 'finish' }] },
    { slug: 'mesquita-vs-rendon', fighter1: 'Bia Mesquita', fighter2: 'Montse Rendon', rewatch_rating: 4, rewatch_label: 'Worth It', category: 'masterclass', why_watch: 'A grappling clinic. Mesquita took the back in under a minute. Short but technically beautiful.', key_moments: [{ timestamp: 'R1 0:45', description: 'Takedown to back take', moment_type: 'takedown' }, { timestamp: 'R1 2:07', description: 'RNC finish', moment_type: 'finish' }] },
    { slug: 'smith-vs-you', fighter1: 'Elijah Smith', fighter2: 'SuYoung You', rewatch_rating: 3, rewatch_label: 'Good', category: 'finish', why_watch: 'Smith showed maturity beyond his 23 years. Found the takedown and locked in the choke.', key_moments: [{ timestamp: 'R2 1:04', description: 'RNC finish from back control', moment_type: 'finish' }] },
    { slug: 'lemos-vs-robertson', fighter1: 'Amanda Lemos', fighter2: 'Gillian Robertson', rewatch_rating: 3, rewatch_label: 'Good', category: 'technical', why_watch: 'A masterclass in neutralizing a striker with wrestling. Study material for grappling gameplans.', key_moments: [{ timestamp: 'R1 1:30', description: "Robertson's first takedown sets the tone", moment_type: 'takedown' }] },
    { slug: 'fili-vs-delgado', fighter1: 'Andre Fili', fighter2: 'Jose Miguel Delgado', rewatch_rating: 3, rewatch_label: 'Good', category: 'technical', why_watch: 'Competitive split decision. The judges were split for a reason.', key_moments: [{ timestamp: 'R2 3:00', description: "Delgado's best round", moment_type: 'exchange' }] },
    { slug: 'johnson-vs-silva', fighter1: 'Charles Johnson', fighter2: 'Bruno Silva', rewatch_rating: 2, rewatch_label: 'Fans Only', category: 'technical', why_watch: 'Competitive flyweight bout. Wrestling was the difference but not many exciting moments.', key_moments: [] },
    { slug: 'curtis-vs-orolbai', fighter1: 'Chris Curtis', fighter2: 'Myktybek Orolbai', rewatch_rating: 2, rewatch_label: 'Fans Only', category: 'boring', why_watch: 'Orolbai dominated but the fight lacked drama. Curtis called it boring himself.', key_moments: [] },
  ],
};

export default async function RecapEmmettVsVallejosPage() {
  const enrichedData = await enrichRecapWithPhotos(recapData);
  return <RecapView data={enrichedData} />;
}
