import { PrelimsAnalysisView } from '@/components/analise/PrelimsAnalysisView';
import type { PrelimsAnalise } from '@/types/analise';

const analise: PrelimsAnalise = {
  id: 'wood-vs-keita',
  evento_id: null,
  slug: 'wood-vs-keita',
  titulo: 'Wood vs Keita',
  subtitulo: null,
  lutador1_id: null,
  lutador2_id: null,
  artigo_conteudo: '',
  tactical_breakdown: {
    stats: [],
    radarData: [],
    taleOfTape: {
      fighter1: { altura: '', envergadura: '', idade: 0, academia: '' },
      fighter2: { altura: '', envergadura: '', idade: 0, academia: '' },
    },
    pathsToVictory: { fighter1: [], fighter2: [] },
    dangerZones: [],
  },
  fight_prediction: {
    predictedWinner: 'fighter1',
    predictedMethod: 'Decisao Unanime',
    confidence: 'MEDIA',
    fighter1Scenarios: [],
    fighter2Scenarios: [],
    keyFactors: [],
    xFactor: { title: '', description: '' },
  },
  fighter1_info: {
    nome: 'Nathaniel Wood',
    record: '22-6-0',
    ultimasLutas: [],
  },
  fighter2_info: {
    nome: 'Losene Keita',
    record: '16-1-0',
    ultimasLutas: [],
  },
  evento_nome: 'UFC Fight Night: Evloev vs Murphy',
  evento_data: '21 de Marco, 2026',
  evento_local: 'The O2 Arena, Londres, Reino Unido',
  categoria_peso: 'Peso Pena (145 lbs)',
  num_rounds: 3,
  is_titulo: false,
  broadcast: null,
  status: 'published',
  analysis_type: 'prelims',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),

  prelims_analysis: {
    hero: {
      evento_nome: 'UFC Fight Night: Evloev vs Murphy',
      evento_data: '21 de Marco, 2026',
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      is_titulo: false,
      fighter1: {
        nome: 'Wood',
        record: '22-6-0',
        ranking: undefined,
      },
      fighter2: {
        nome: 'Keita',
        record: '16-1-0',
        ranking: undefined,
      },
    },

    comparacao_estatistica: {
      stats: [
        {
          label: 'Sig. Strikes por Minuto',
          valueA: 5.75,
          valueB: 4.80,
          maxVal: 8,
          format: 'decimal',
          note: 'Wood e uma metralhadora na trocacao, quase 6 golpes significativos por minuto',
        },
        {
          label: 'Precisao de Strikes (%)',
          valueA: 48,
          valueB: 52,
          maxVal: 100,
          format: 'percent',
          note: 'Keita conecta com mais precisao, reflexo de seu background no boxe',
        },
        {
          label: 'Strikes Absorvidos/Min',
          valueA: 4.10,
          valueB: 3.50,
          maxVal: 7,
          format: 'decimal',
          reverseWinner: true,
          note: 'Keita absorve menos golpes, indicando movimentacao superior',
        },
        {
          label: 'Defesa de Strikes (%)',
          valueA: 55,
          valueB: 58,
          maxVal: 100,
          format: 'percent',
        },
        {
          label: 'Takedowns por 15 Min',
          valueA: 1.50,
          valueB: 0.80,
          maxVal: 5,
          format: 'decimal',
          note: 'Wood tem background de grappling mais solido e usa quedas para controlar',
        },
        {
          label: 'Precisao de Takedown (%)',
          valueA: 73,
          valueB: 40,
          maxVal: 100,
          format: 'percent',
          note: 'Wood tem precisao elite nos takedowns, conecta quase 3 em cada 4 tentativas',
        },
        {
          label: 'Defesa de Takedown (%)',
          valueA: 72,
          valueB: 68,
          maxVal: 100,
          format: 'percent',
        },
      ],
      tale_of_tape: [
        { label: 'Idade', fighter1: '32 anos', fighter2: '28 anos', note: 'Keita tem 4 anos a menos' },
        { label: 'Altura', fighter1: '1,68m (5\'6")', fighter2: '1,76m (5\'9")', note: 'Keita tem 8cm de vantagem na altura' },
        { label: 'Envergadura', fighter1: '175cm (68.9")', fighter2: '176cm (69.3")', note: null },
        { label: 'Stance', fighter1: 'Ortodoxo', fighter2: 'Ortodoxo', note: null },
        { label: 'Academia', fighter1: 'London Shootfighters / Londres', fighter2: 'Lamiro Fight Club / Kortrijk, Belgica', note: null },
      ],
    },

    historico_lutas: {
      fighter1: {
        nome: 'Wood',
        recent_fights: [
          {
            date: 'Out 2025',
            opponent: 'Jose Miguel Delgado',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Vitoria segura por pontos no UFC 321, manteve sequencia de 3 vitorias consecutivas.',
          },
          {
            date: 'Mar 2025',
            opponent: 'Morgan Charriere',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 3,
            quality_label: 'Bom',
            note: 'Superou o frances em sua casa no UFC Paris, demonstrando maturidade e controle tatico.',
          },
          {
            date: 'Jul 2024',
            opponent: 'Daniel Pineda',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Vitoria no UFC 304 em Manchester, manteve ritmo alto por 3 rounds diante da torcida inglesa.',
          },
          {
            date: 'Mar 2024',
            opponent: 'Lerone Murphy',
            result: 'L',
            method: 'TKO R3',
            opponent_rank: '#14 FW',
            quality_score: 4,
            quality_label: 'Muito Bom',
            note: 'Luta equilibrada ate ser finalizado no terceiro round contra rival local de Manchester.',
          },
          {
            date: 'Set 2023',
            opponent: 'Jafel Filho',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Voltou a vencer com performance solida no UFC Paris, controle por pontos.',
          },
        ],
      },
      fighter2: {
        nome: 'Keita',
        recent_fights: [
          {
            date: 'Set 2025',
            opponent: 'Patricio Pitbull',
            result: 'NC',
            method: 'Cancelado (excesso peso)',
            opponent_rank: 'N/R',
            quality_score: 3,
            quality_label: 'Bom',
            note: 'Estreia no UFC cancelada por pesar 149lbs, 3 libras acima do limite. Sinal de alerta na disciplina.',
          },
          {
            date: 'Dez 2024',
            opponent: 'Ronald Paradeiser',
            result: 'W',
            method: 'TKO R3',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Final do torneio Oktagon e titulo dos meio-leves. Conquista tripla coroa: 2x peso leve + peso pena.',
          },
          {
            date: 'Set 2024',
            opponent: 'Mateusz Legierski',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Semifinal do torneio Oktagon, vitoria calculada por pontos contra polones.',
          },
          {
            date: 'Jul 2024',
            opponent: 'Predrag Bogdanovic',
            result: 'W',
            method: 'KO R2',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Nocaute devastador nas quartas de final do torneio Oktagon.',
          },
          {
            date: 'Jun 2022',
            opponent: 'Ivan Buchinger',
            result: 'W',
            method: 'TKO R1',
            opponent_rank: 'Campeao Oktagon',
            quality_score: 3,
            quality_label: 'Bom',
            note: 'Destronou o duplo campeao Buchinger no primeiro round para conquistar o titulo.',
          },
        ],
      },
    },

    perfil_habilidades: {
      skills: [
        {
          label: 'Striking em Pe',
          valueA: 82,
          valueB: 80,
          labelA: 'Muito Bom',
          labelB: 'Muito Bom',
          advantage: 'even',
          advantage_note: 'Wood tem volume absurdo com 5.75 SLpM. Keita tem 10 KOs na carreira e precisao superior. Trocacao de altissimo nivel.',
        },
        {
          label: 'Poder de Nocaute',
          valueA: 65,
          valueB: 85,
          labelA: 'Bom',
          labelB: 'Muito Bom',
          advantage: 'fighter2',
          advantage_note: 'Keita tem 10 nocautes em 16 vitorias (63%), incluindo nocautes no R1 contra campeoes. Wood tem 8 KOs mas contra adversarios inferiores.',
        },
        {
          label: 'Wrestling e Grappling',
          valueA: 76,
          valueB: 55,
          labelA: 'Muito Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Wood tem 73% de precisao de takedown e 5 finalizacoes na carreira. Keita e principalmente um striker com pouco grappling ofensivo.',
        },
        {
          label: 'Defesa Geral',
          valueA: 72,
          valueB: 65,
          labelA: 'Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Wood tem defesa de takedown de 72% e mais experiencia defensiva. Keita nunca foi testado por um grappler de elite.',
        },
        {
          label: 'Cardio e Ritmo',
          valueA: 80,
          valueB: 72,
          labelA: 'Muito Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Wood mantem ritmo alto por 3 rounds inteiros, suas ultimas 3 vitorias foram todas por decisao unanime.',
        },
        {
          label: 'Experiencia no Octagon',
          valueA: 85,
          valueB: 25,
          labelA: 'Muito Bom',
          labelB: 'Ruim',
          advantage: 'fighter1',
          advantage_note: 'Wood tem 13 lutas no UFC (10V-3D) e ja enfrentou top 15. Keita nunca lutou no Octagon, sua estreia foi cancelada.',
        },
      ],
      insight: 'Wood e o lutador mais completo e experiente, com vantagens claras no grappling, cardio e maturidade no Octagon. Keita traz poder explosivo de nocaute e a confianca de um campeao invicto, mas a transicao do Oktagon para o UFC e um salto enorme. A chave e se Keita consegue conectar limpo nos dois primeiros rounds antes que o cardio de Wood tome conta.',
    },

    distribuicao_vitorias: {
      fighter1: {
        nome: 'Wood',
        ko_tko: { count: 8, percent: 36 },
        submission: { count: 5, percent: 23 },
        decision: { count: 9, percent: 41 },
        total_wins: 22,
      },
      fighter2: {
        nome: 'Keita',
        ko_tko: { count: 10, percent: 63 },
        submission: { count: 2, percent: 12 },
        decision: { count: 4, percent: 25 },
        total_wins: 16,
      },
      insight: 'Perfis opostos na forma de vencer. Wood e bem distribuido entre decisao (41%), KO (36%) e finalizacao (23%), mostrando versatilidade total. Keita e um finalizador nato com 63% de nocautes, um dos maiores indices da divisao. Se a luta for para a distancia, favorece Wood. Se Keita conectar cedo, pode acabar rapido.',
    },

    previsao_final: {
      winner_name: 'Wood',
      winner_side: 'fighter1',
      predicted_method: 'Decisao Unanime',
      confidence_score: 6,
      confidence_label: 'MEDIA',
      explanation: 'Nathaniel Wood luta em casa em Londres com 3 vitorias consecutivas e 13 lutas de experiencia no Octagon. Keita e talentoso e perigoso, mas nunca pisou no cage do UFC e perdeu sua unica chance de estrear por nao bater o peso. A pressao de uma estreia em territorio hostil, combinada com o ritmo implacavel de Wood e seu grappling superior, devem ser fatores decisivos. Porem, o poder de Keita e real e Wood ja mostrou vulnerabilidade contra strikers pesados como Murphy.',
      x_factor: {
        title: 'Londres e a torcida de Wood',
        description: 'Wood nunca perdeu em casa na Inglaterra pelo UFC. A energia da O2 Arena vai empurrar o ingles, especialmente nos rounds finais quando o cardio pode fazer a diferenca.',
      },
      upset_alert: {
        title: 'Keita tem o poder para apagar qualquer um',
        description: 'Com 10 nocautes em 16 vitorias e finalizacoes contra campeoes, Keita pode resolver a luta com um unico golpe. Se Wood subestimar o poder do belga e entrar na troca franca, pode ser surpreendido como foi por Murphy.',
      },
      probabilities: {
        fighter1: { nome: 'Wood', percent: 62 },
        fighter2: { nome: 'Keita', percent: 36 },
        draw: 2,
      },
      value_picks: undefined,
    },
  },
};

export default function Page() {
  return <PrelimsAnalysisView analise={analise} />;
}
