import { EventAnalysisView, type EventAnalysisData } from '@/components/analise/EventAnalysisView';
import { enrichEventWithPhotos } from '@/lib/enrich-event-photos';

export const dynamic = 'force-dynamic';

const eventData: EventAnalysisData = {
  evento_nome: 'UFC Fight Night: Evloev vs Murphy',
  evento_data: '21 de Marco, 2026',
  evento_local: 'The O2 Arena, Londres, Reino Unido',
  main_card: [
    {
      slug: 'evloev-vs-murphy',
      fighter1: { nome: 'Movsar Evloev', record: '19-0-0' },
      fighter2: { nome: 'Lerone Murphy', record: '17-0-1' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 5,
      predicted_winner: 'Movsar Evloev',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
      is_main_event: true,
    },
    {
      slug: 'riley-vs-aswell-jr',
      fighter1: { nome: 'Luke Riley', record: '12-0-0' },
      fighter2: { nome: 'Michael Aswell Jr.', record: '11-3-0' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Luke Riley',
      predicted_method: 'KO/TKO R1-R2',
      confidence_label: 'MEDIA-ALTA',
    },
    {
      slug: 'page-vs-patterson',
      fighter1: { nome: 'Michael Page', record: '24-3-0' },
      fighter2: { nome: 'Sam Patterson', record: '14-2-1' },
      categoria_peso: 'Peso Meio-Medio (170 lbs)',
      num_rounds: 3,
      predicted_winner: 'Sam Patterson',
      predicted_method: 'Submissao R1-R2',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'baraniewski-vs-lane',
      fighter1: { nome: 'Iwo Baraniewski', record: '7-0-0' },
      fighter2: { nome: 'Austen Lane', record: '13-7-0' },
      categoria_peso: 'Peso Meio-Pesado (205 lbs)',
      num_rounds: 3,
      predicted_winner: 'Iwo Baraniewski',
      predicted_method: 'KO/TKO R1',
      confidence_label: 'MEDIA-ALTA',
    },
    {
      slug: 'dolidze-vs-duncan',
      fighter1: { nome: 'Roman Dolidze', record: '15-4-0' },
      fighter2: { nome: 'Christian Leroy Duncan', record: '13-2-0' },
      categoria_peso: 'Peso Medio (185 lbs)',
      num_rounds: 3,
      predicted_winner: 'Christian Leroy Duncan',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'campbell-vs-silva',
      fighter1: { nome: 'Kurtis Campbell', record: '8-0-0' },
      fighter2: { nome: 'Danny Silva', record: '10-2-0' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Kurtis Campbell',
      predicted_method: 'KO/TKO R1-R2',
      confidence_label: 'MEDIA',
    },
  ],
  prelims: [
    {
      slug: 'jones-vs-sola',
      fighter1: { nome: 'Mason Jones', record: '17-2-0' },
      fighter2: { nome: 'Axel Sola', record: '11-0-1' },
      categoria_peso: 'Peso Leve (155 lbs)',
      num_rounds: 3,
      predicted_winner: 'Mason Jones',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'wood-vs-keita',
      fighter1: { nome: 'Nathaniel Wood', record: '22-6-0' },
      fighter2: { nome: 'Losene Keita', record: '16-1-0' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Nathaniel Wood',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'sutherland-vs-pericic',
      fighter1: { nome: 'Louie Sutherland', record: '10-4-0' },
      fighter2: { nome: 'Brando Pericic', record: '5-1-0' },
      categoria_peso: 'Peso Pesado (265 lbs)',
      num_rounds: 3,
      predicted_winner: 'Brando Pericic',
      predicted_method: 'KO/TKO R1',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'kondratavicius-vs-trocoli',
      fighter1: { nome: 'Mantas Kondratavicius', record: '8-1-0' },
      fighter2: { nome: 'Antonio Trocoli', record: '12-6-0' },
      categoria_peso: 'Peso Medio (185 lbs)',
      num_rounds: 3,
      predicted_winner: 'Mantas Kondratavicius',
      predicted_method: 'KO/TKO R1',
      confidence_label: 'MEDIA-ALTA',
    },
    {
      slug: 'pinto-vs-franco',
      fighter1: { nome: 'Mario Pinto', record: '11-0-0' },
      fighter2: { nome: 'Felipe Franco', record: '10-1-0' },
      categoria_peso: 'Peso Pesado (265 lbs)',
      num_rounds: 3,
      predicted_winner: 'Mario Pinto',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIA-ALTA',
    },
    {
      slug: 'rock-vs-al-selwady',
      fighter1: { nome: 'Shem Rock', record: '12-2-1' },
      fighter2: { nome: 'Abdul-Kareem Al-Selwady', record: '15-4-0' },
      categoria_peso: 'Peso Leve (155 lbs)',
      num_rounds: 3,
      predicted_winner: 'Abdul-Kareem Al-Selwady',
      predicted_method: 'KO/TKO R2',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'dyer-vs-oliveira',
      fighter1: { nome: 'Shanelle Dyer', record: '6-1-0' },
      fighter2: { nome: 'Ravena Oliveira', record: '7-3-1' },
      categoria_peso: 'Peso Palha Feminino (115 lbs)',
      num_rounds: 3,
      predicted_winner: 'Shanelle Dyer',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'mullins-vs-carolina',
      fighter1: { nome: 'Melissa Mullins', record: '7-2-0' },
      fighter2: { nome: 'Luana Carolina', record: '11-5-0' },
      categoria_peso: 'Peso Galo Feminino (135 lbs)',
      num_rounds: 3,
      predicted_winner: 'Luana Carolina',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
  ],
};

export default async function EventoEvloevVsMurphyPage() {
  const enrichedData = await enrichEventWithPhotos(eventData);
  return <EventAnalysisView data={enrichedData} />;
}
