import { PrelimsAnalysisView } from '@/components/analise/PrelimsAnalysisView';
import type { PrelimsAnalise } from '@/types/analise';

const analise: PrelimsAnalise = {
  id: 'sutherland-vs-pericic',
  evento_id: null,
  slug: 'sutherland-vs-pericic',
  titulo: 'Sutherland vs Pericic',
  subtitulo: null,
  lutador1_id: null,
  lutador2_id: null,
  artigo_conteudo: '',
  tactical_breakdown: {
    stats: [],
    radarData: [],
    taleOfTape: {
      fighter1: { altura: '', envergadura: '', idade: 0, academia: '' },
      fighter2: { altura: '', envergadura: '', idade: 0, academia: '' },
    },
    pathsToVictory: { fighter1: [], fighter2: [] },
    dangerZones: [],
  },
  fight_prediction: {
    predictedWinner: 'fighter2',
    predictedMethod: 'KO/TKO R1',
    confidence: 'MEDIA',
    fighter1Scenarios: [],
    fighter2Scenarios: [],
    keyFactors: [],
    xFactor: { title: '', description: '' },
  },
  fighter1_info: {
    nome: 'Louie Sutherland',
    record: '10-4-0',
    ultimasLutas: [],
  },
  fighter2_info: {
    nome: 'Brando Pericic',
    record: '5-1-0',
    ultimasLutas: [],
  },
  evento_nome: 'UFC Fight Night: Evloev vs Murphy',
  evento_data: '21 de Marco, 2026',
  evento_local: 'The O2 Arena, Londres, Reino Unido',
  categoria_peso: 'Peso Pesado (265 lbs)',
  num_rounds: 3,
  is_titulo: false,
  broadcast: null,
  status: 'published',
  analysis_type: 'prelims',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),

  prelims_analysis: {
    hero: {
      evento_nome: 'UFC Fight Night: Evloev vs Murphy',
      evento_data: '21 de Marco, 2026',
      categoria_peso: 'Peso Pesado (265 lbs)',
      num_rounds: 3,
      is_titulo: false,
      fighter1: {
        nome: 'Sutherland',
        record: '10-4-0',
        ranking: undefined,
      },
      fighter2: {
        nome: 'Pericic',
        record: '5-1-0',
        ranking: undefined,
      },
    },

    comparacao_estatistica: {
      stats: [
        {
          label: 'Sig. Strikes por Minuto',
          valueA: 4.20,
          valueB: 6.15,
          maxVal: 8,
          format: 'decimal',
          note: 'Pericic tem volume explosivo, mais de 6 strikes significativos por minuto na estreia',
        },
        {
          label: 'Precisao de Strikes (%)',
          valueA: 45,
          valueB: 55,
          maxVal: 100,
          format: 'percent',
          note: 'Pericic conecta com mais precisao, fruto do background de kickboxing profissional',
        },
        {
          label: 'Strikes Absorvidos/Min',
          valueA: 3.80,
          valueB: 2.50,
          maxVal: 7,
          format: 'decimal',
          reverseWinner: true,
          note: 'Pericic absorve muito menos golpes, finalizou rapido sem dar tempo de reacao',
        },
        {
          label: 'Defesa de Strikes (%)',
          valueA: 48,
          valueB: 60,
          maxVal: 100,
          format: 'percent',
          note: 'Sutherland tem defesa abaixo da media, foi finalizado por heel hook recentemente',
        },
        {
          label: 'Takedowns por 15 Min',
          valueA: 1.80,
          valueB: 0.50,
          maxVal: 5,
          format: 'decimal',
          note: 'Sutherland tenta mais takedowns, pode ser seu caminho para a vitoria',
        },
        {
          label: 'Precisao de Takedown (%)',
          valueA: 42,
          valueB: 33,
          maxVal: 100,
          format: 'percent',
        },
        {
          label: 'Defesa de Takedown (%)',
          valueA: 55,
          valueB: 70,
          maxVal: 100,
          format: 'percent',
          note: 'Pericic treina com Israel Adesanya e equipe de elite do City Kickboxing',
        },
      ],
      tale_of_tape: [
        { label: 'Idade', fighter1: '32 anos', fighter2: '24 anos', note: '8 anos de diferenca, Pericic bem mais jovem' },
        { label: 'Altura', fighter1: '1,91m (6\'3")', fighter2: '1,96m (6\'5")', note: 'Pericic tem 5cm de vantagem' },
        { label: 'Envergadura', fighter1: '193cm (76")', fighter2: '198cm (78")', note: 'Pericic tem 5cm a mais de envergadura' },
        { label: 'Stance', fighter1: 'Ortodoxo', fighter2: 'Ortodoxo', note: null },
        { label: 'Academia', fighter1: 'Team Sherdog / Inglaterra', fighter2: 'City Kickboxing / Auckland, NZ', note: 'Pericic treina com Adesanya e Volk' },
      ],
    },

    historico_lutas: {
      fighter1: {
        nome: 'Sutherland',
        recent_fights: [
          {
            date: 'Out 2025',
            opponent: 'Valter Walker',
            result: 'L',
            method: 'Sub R1 (heel hook)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Finalizado com heel hook em apenas 1:24 do primeiro round no UFC 321. Derrota preocupante.',
          },
          {
            date: 'Jun 2025',
            opponent: 'Karl Williams',
            result: 'W',
            method: 'KO R1',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Nocaute rapido no primeiro round, mostrou poder nas maos contra adversario limitado.',
          },
          {
            date: 'Mar 2025',
            opponent: 'Jamal Pogues',
            result: 'W',
            method: 'TKO R2',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'TKO no segundo round no DWCS, garantiu contrato com o UFC.',
          },
          {
            date: 'Nov 2024',
            opponent: 'Archie Sheridan',
            result: 'W',
            method: 'KO R1',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Nocaute no Cage Warriors, nivel de oposicao regional.',
          },
          {
            date: 'Jul 2024',
            opponent: 'Alain Ilunga',
            result: 'L',
            method: 'KO R1',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Nocauteado no PFL, mostrou vulnerabilidade defensiva contra striker.',
          },
        ],
      },
      fighter2: {
        nome: 'Pericic',
        recent_fights: [
          {
            date: 'Set 2025',
            opponent: 'Elisha Ellison',
            result: 'W',
            method: 'TKO R1 (1:55)',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Estreia explosiva no UFC em Perth. Derrubou e finalizou com ground-and-pound em menos de 2 minutos. Performance of the Night.',
          },
          {
            date: 'Jun 2025',
            opponent: 'Tyson Pedro',
            result: 'L',
            method: 'KO R1',
            opponent_rank: 'N/R',
            quality_score: 3,
            quality_label: 'Bom',
            note: 'Unica derrota da carreira. Nocauteado por Pedro em combate regional na Australia.',
          },
          {
            date: 'Mar 2025',
            opponent: 'Ben Kelleher',
            result: 'W',
            method: 'TKO R1',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Nocaute rapido no primeiro round, continuou empilhando vitorias no circuito australiano.',
          },
          {
            date: 'Dez 2024',
            opponent: 'Myles Morales',
            result: 'W',
            method: 'Sub R1 (guilhotina)',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Finalizacao por guilhotina no primeiro round, mostrou versatilidade alem do striking.',
          },
          {
            date: 'Ago 2024',
            opponent: 'Beau Hartas',
            result: 'W',
            method: 'KO R1',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Nocaute no primeiro round no circuito australiano, todas as vitorias sao finalizacoes rapidas.',
          },
        ],
      },
    },

    perfil_habilidades: {
      skills: [
        {
          label: 'Striking em Pe',
          valueA: 62,
          valueB: 82,
          labelA: 'Bom',
          labelB: 'Muito Bom',
          advantage: 'fighter2',
          advantage_note: 'Pericic tem 18-2 no kickboxing profissional com multiplos titulos. Striking e sua arma principal e esta em outro patamar tecnico.',
        },
        {
          label: 'Poder de Nocaute',
          valueA: 72,
          valueB: 85,
          labelA: 'Bom',
          labelB: 'Muito Bom',
          advantage: 'fighter2',
          advantage_note: 'Pericic tem 80% de vitorias por KO/TKO. Sutherland tambem tem poder, mas e menos consistente.',
        },
        {
          label: 'Wrestling e Grappling',
          valueA: 50,
          valueB: 48,
          labelA: 'Medio',
          labelB: 'Medio',
          advantage: 'even',
          advantage_note: 'Ambos sao principalmente strikers. Nenhum dos dois tem wrestling de alto nivel, mas Sutherland tenta mais takedowns.',
        },
        {
          label: 'Defesa Geral',
          valueA: 42,
          valueB: 60,
          labelA: 'Medio',
          labelB: 'Bom',
          advantage: 'fighter2',
          advantage_note: 'Sutherland foi finalizado por heel hook e nocauteado pelo PFL. Pericic treina com elite do CKB e absorve menos golpes.',
        },
        {
          label: 'Cardio e Ritmo',
          valueA: 50,
          valueB: 55,
          labelA: 'Medio',
          labelB: 'Bom',
          advantage: 'fighter2',
          advantage_note: 'Como peso pesado, ambos preferem resolver cedo. Pericic nunca passou do R1 nas suas vitorias.',
        },
        {
          label: 'Experiencia no Octagon',
          valueA: 45,
          valueB: 35,
          labelA: 'Medio',
          labelB: 'Medio',
          advantage: 'fighter1',
          advantage_note: 'Sutherland tem 3 lutas no UFC (2V-1D), Pericic tem apenas 1 vitoria. Ambos sao relativamente novos no Octagon.',
        },
      ],
      insight: 'Pericic e tecnicamente superior no striking com background de kickboxing profissional e treinamento na elite do City Kickboxing. Sutherland tem poder mas e inconsistente defensivamente. Esta luta provavelmente nao vai para os cartoes.',
    },

    distribuicao_vitorias: {
      fighter1: {
        nome: 'Sutherland',
        ko_tko: { count: 7, percent: 70 },
        submission: { count: 1, percent: 10 },
        decision: { count: 2, percent: 20 },
        total_wins: 10,
      },
      fighter2: {
        nome: 'Pericic',
        ko_tko: { count: 4, percent: 80 },
        submission: { count: 1, percent: 20 },
        decision: { count: 0, percent: 0 },
        total_wins: 5,
      },
      insight: 'Dois nocauteadores na divisao mais pesada do UFC. Sutherland tem 70% de KOs e Pericic impressionantes 80%, com zero vitorias por decisao. Pericic nunca precisou dos juizes para vencer. Esta luta tem tudo para acabar antes do gongo final.',
    },

    previsao_final: {
      winner_name: 'Pericic',
      winner_side: 'fighter2',
      predicted_method: 'KO/TKO R1',
      confidence_score: 6,
      confidence_label: 'MEDIA',
      explanation: 'Brando Pericic tem vantagem tecnica clara no striking com background de kickboxing profissional (18-2) e treinamento no City Kickboxing com Israel Adesanya. Sutherland tem poder mas e vulneravel defensivamente, tendo sido nocauteado pelo PFL e finalizado por heel hook no UFC. Pericic e mais jovem, mais alto, tem mais alcance e treina com uma equipe de nivel mundial. A unica chance de Sutherland e conectar um golpe limpo aproveitando a torcida em casa, mas Pericic deve ser tecnico demais para permitir isso.',
      x_factor: {
        title: 'O treinamento do City Kickboxing',
        description: 'Pericic treina diariamente com ex-campeoes como Adesanya e Volkanovski. Esse nivel de sparring prepara para qualquer adversario, especialmente contra um striker menos tecnico como Sutherland.',
      },
      upset_alert: {
        title: 'Sutherland em casa com a torcida',
        description: 'Sutherland luta na Inglaterra com o apoio da O2 Arena. Ele tem poder real nas maos e, como peso pesado, um unico soco pode mudar tudo. Se conectar cedo antes de Pericic encontrar seu ritmo, pode surpreender.',
      },
      probabilities: {
        fighter1: { nome: 'Sutherland', percent: 35 },
        fighter2: { nome: 'Pericic', percent: 63 },
        draw: 2,
      },
      value_picks: undefined,
    },
  },
};

export default function Page() {
  return <PrelimsAnalysisView analise={analise} />;
}
