import { translateAnalysis } from '@/lib/translate-analysis';
import { EventAnalysisView, type EventAnalysisData } from '@/components/analise/EventAnalysisView';
import { enrichEventWithPhotos } from '@/lib/enrich-event-photos';
import type { EventCreatorKitData } from '@/types/event-creator-kit';

export const dynamic = 'force-dynamic';

const eventData: EventAnalysisData = {
  evento_nome: 'UFC Fight Night: Adesanya vs Pyfer',
  evento_data: '28 de Marco, 2026',
  evento_local: 'Climate Pledge Arena, Seattle, Washington',
  main_card: [
    {
      slug: 'adesanya-vs-pyfer',
      fighter1: { nome: 'Israel Adesanya', record: '24-5-0' },
      fighter2: { nome: 'Joe Pyfer', record: '15-3-0' },
      categoria_peso: 'Peso Medio (185 lbs)',
      num_rounds: 5,
      predicted_winner: 'Israel Adesanya',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
      is_main_event: true,
    },
    {
      slug: 'grasso-vs-barber',
      fighter1: { nome: 'Alexa Grasso', record: '16-4-1' },
      fighter2: { nome: 'Maycee Barber', record: '16-3-0' },
      categoria_peso: 'Peso Mosca Feminino (125 lbs)',
      num_rounds: 3,
      predicted_winner: 'Maycee Barber',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'chiesa-vs-price',
      fighter1: { nome: 'Michael Chiesa', record: '19-7-0' },
      fighter2: { nome: 'Niko Price', record: '16-10-0' },
      categoria_peso: 'Peso Meio-Medio (170 lbs)',
      num_rounds: 3,
      predicted_winner: 'Michael Chiesa',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA-ALTA',
    },
    {
      slug: 'erosa-vs-douglas',
      fighter1: { nome: 'Julian Erosa', record: '32-13-0' },
      fighter2: { nome: 'Lerryan Douglas', record: '13-5-0' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Julian Erosa',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'abdul-malik-vs-belgaroui',
      fighter1: { nome: 'Mansur Abdul-Malik', record: '9-0-1' },
      fighter2: { nome: 'Yousri Belgaroui', record: '11-2-0' },
      categoria_peso: 'Peso Medio (185 lbs)',
      num_rounds: 3,
      predicted_winner: 'Yousri Belgaroui',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'mckinney-vs-nelson',
      fighter1: { nome: 'Terrance McKinney', record: '16-8-0' },
      fighter2: { nome: 'Kyle Nelson', record: '17-6-1' },
      categoria_peso: 'Peso Leve (155 lbs)',
      num_rounds: 3,
      predicted_winner: 'Terrance McKinney',
      predicted_method: 'KO/TKO R1',
      confidence_label: 'MEDIA',
    },
  ],
  prelims: [
    {
      slug: 'musayev-vs-bahamondes',
      fighter1: { nome: 'Tofiq Musayev', record: '22-6-0' },
      fighter2: { nome: 'Ignacio Bahamondes', record: '17-6-0' },
      categoria_peso: 'Peso Leve (155 lbs)',
      num_rounds: 3,
      predicted_winner: 'Ignacio Bahamondes',
      predicted_method: 'KO/TKO R2',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'hooper-vs-gibson',
      fighter1: { nome: 'Chase Hooper', record: '14-5-1' },
      fighter2: { nome: 'Lance Gibson Jr.', record: '9-2-0' },
      categoria_peso: 'Peso Leve (155 lbs)',
      num_rounds: 3,
      predicted_winner: 'Chase Hooper',
      predicted_method: 'Submissao R2',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'tybura-vs-fortune',
      fighter1: { nome: 'Marcin Tybura', record: '25-9-0' },
      fighter2: { nome: 'Tyrell Fortune', record: '17-3-0' },
      categoria_peso: 'Peso Pesado (265 lbs)',
      num_rounds: 3,
      predicted_winner: 'Tyrell Fortune',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'oneill-vs-fernandes',
      fighter1: { nome: 'Casey O\'Neill', record: '10-2-0' },
      fighter2: { nome: 'Gabriella Fernandes', record: '11-3-0' },
      categoria_peso: 'Peso Mosca Feminino (125 lbs)',
      num_rounds: 3,
      predicted_winner: 'Casey O\'Neill',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'lopes-vs-stirling',
      fighter1: { nome: 'Bruno Lopes', record: '12-2-0' },
      fighter2: { nome: 'Navajo Stirling', record: '10-1-0' },
      categoria_peso: 'Peso Meio-Pesado (205 lbs)',
      num_rounds: 3,
      predicted_winner: 'Navajo Stirling',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'simon-vs-yanez',
      fighter1: { nome: 'Ricky Simon', record: '21-6-0' },
      fighter2: { nome: 'Adrian Yanez', record: '18-5-0' },
      categoria_peso: 'Peso Galo (135 lbs)',
      num_rounds: 3,
      predicted_winner: 'Adrian Yanez',
      predicted_method: 'KO/TKO R2',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'brasil-vs-thainara',
      fighter1: { nome: 'Bruna Brasil', record: '11-4-1' },
      fighter2: { nome: 'Alexia Thainara', record: '5-2-0' },
      categoria_peso: 'Peso Palha Feminino (115 lbs)',
      num_rounds: 3,
      predicted_winner: 'Bruna Brasil',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
  ],
  creator_kit: {
    instagram: {
      meta: {
        algorithm_tip: 'Carroseis com 7-10 slides geram 95% mais saves. O Instagram re-exibe carroseis que nao foram swipados. Posts sobre ex-campeoes e comebacks geram engagement massivo.',
        target_metric: '60%+ taxa de swipe, 3%+ taxa de save',
        content_type: 'Carrossel de 10 slides (formato 4:5, 1080x1350px)',
      },
      carousel: [
        { slide_number: 1, slide_type: 'hook', title: 'UFC SEATTLE', content: 'O EX-CAMPEAO VOLTOU.\n\nAdesanya (24-5) vs Pyfer (15-3)\nGrasso vs Barber II (revanche)\nChiesa: luta de aposentadoria\n\n13 lutas. Sabado.\nSwipe pra saber tudo.', visual_note: 'Adesanya em postura iconica, octogono desfocado. Titulo "O EX-CAMPEAO VOLTOU" em vermelho grande.', color: 'red' },
        { slide_number: 2, slide_type: 'content', title: 'ADESANYA: A REDENCAO', content: 'Israel "Stylebender" Adesanya\n24-5 | Ex-bicampeao peso-medio\n\n3 DERROTAS SEGUIDAS:\nStrickland (decisao)\nDu Plessis (sub R4)\nImavov (TKO R2)\n\n13 meses sem lutar.\n36 anos. Ultima chance?\n\nContra Pyfer: 15-3, 3 vitorias seguidas,\npower puncher de 29 anos.', visual_note: 'Timeline visual: titulo > 5 defesas > 3 derrotas. Adesanya com expressao determinada.', color: 'red' },
        { slide_number: 3, slide_type: 'stat', title: 'O DADO QUE ASSUSTA', content: 'Adesanya: 13 knockdowns no UFC\nEmpatado com Anderson Silva\nRECORDE DA DIVISAO.\n\nMas os ultimos 3 oponentes\nmostraram que o queixo\nde Izzy nao e o mesmo.\n\nImavov: TKO R2\nDu Plessis: Sub R4\n\nPyfer tem 1.2 knockdowns\npor 15 minutos. Top 4 MW.', visual_note: 'Grafico de knockdowns comparativo. Records historicos.', color: 'gold' },
        { slide_number: 4, slide_type: 'content', title: 'GRASSO vs BARBER II', content: 'REVANCHE.\n\nGrasso venceu em 2021.\nMas desde entao:\n\nGrasso: Perdeu o titulo, 2 derrotas seguidas\nBarber: 7 VITORIAS SEGUIDAS, favorita -160\n\nQuem mudou mais em 5 anos?', visual_note: 'Split face das duas. Timeline 2021 vs 2026 com trajetorias opostas.', color: 'blue' },
        { slide_number: 5, slide_type: 'content', title: 'A APOSENTADORIA DE CHIESA', content: 'Michael Chiesa anunciou:\nessa e a ULTIMA luta.\n\nEm casa, em Seattle.\n19-7 na carreira.\n3 vitorias seguidas (Ferguson, Griffin, McGee).\n\nContra Niko Price (short notice)\nque esta 2-7 nos ultimos 6 anos.\n\nO adeus do "Maverick".', visual_note: 'Chiesa com expressao emotiva. Seattle skyline ao fundo. Badge "RETIREMENT FIGHT".', color: 'blue' },
        { slide_number: 6, slide_type: 'content', title: 'PROSPECTS E VETERANOS', content: 'McKinney: 100% finish rate\nvs Nelson: 4 de 5 no UFC\n\nAbdul-Malik: 9-0-1 invicto\nvs Belgaroui: treina com Pereira\n\nErosa: luta em casa em Seattle\nvs Douglas: 5 KOs seguidos (13-5)\n\nHooper: jiu-jitsu de elite\nvs Gibson Jr: filho de lenda do MMA', visual_note: 'Grid 2x2 com as 4 lutas e fotos dos lutadores.', color: 'gold' },
        { slide_number: 7, slide_type: 'stat', title: 'MUSAYEV: O EX-CAMPEAO RIZIN', content: 'Tofiq Musayev: 22-6\nEx-campeao RIZIN\n18 nocautes em 22 vitorias\n\nPerdeu o debut no UFC\n(sub R1 contra Orolbai)\n\nAgora enfrenta Bahamondes\nque tem 3 finalizacoes no R1\nseguidas.\n\nExplosivo vs Explosivo.', visual_note: 'Musayev com cinturao RIZIN. Bahamondes em postura de striking.', color: 'red' },
        { slide_number: 8, slide_type: 'prediction', title: 'NOSSAS PREVISOES', content: 'MAIN CARD:\nAdesanya por Decisao\nBarber por Decisao\nChiesa por Decisao\nErosa por Decisao\nBelgaroui por Decisao\nMcKinney por KO R1\n\nO main card favorece lutas\nque vao a distancia.\nExceto McKinney, que nao sabe\no que e segundo round.', visual_note: 'Layout de fight card estilizado com nomes e metodos.', color: 'red' },
        { slide_number: 9, slide_type: 'content', title: 'O FATOR SEATTLE', content: 'Lutadores locais:\n\nChiesa (aposentadoria em casa)\nErosa (Portland, proximo)\nHooper (Washington state)\n\nO Climate Pledge Arena\nvai estar LOTADO pro adeus\nde Chiesa e o retorno de Izzy.\n\n13 lutas. Sabado.', visual_note: 'Mapa do Pacific Northwest com pins. Climate Pledge Arena.', color: 'blue' },
        { slide_number: 10, slide_type: 'cta', title: 'ANALISE COMPLETA', content: 'Pre-fight analysis de CADA luta:\n\n15 secoes por luta (main card)\n6 secoes por luta (prelims)\nStats, narrativas, previsoes\nCreator kit pra 5 plataformas\n\nLink na bio.\nSalva pra consultar no sabado.', visual_note: 'Screenshot do site. CTA bold.', color: 'gold' },
      ],
      caption: 'UFC Seattle no sabado: Adesanya voltou. 3 derrotas seguidas, 13 meses parado, 36 anos. Contra Pyfer, um power puncher de 29 anos em sequencia de 3 vitorias.\n\nGrasso vs Barber e a revanche de 5 anos. Chiesa se aposenta em casa. McKinney promete mais um nocaute relampago.\n\nSwipe pra ver as historias, os dados e as previsoes de todas as 13 lutas.\n\nSalva pra consultar durante o card.',
      hashtags: ['UFC', 'UFCSeattle', 'Adesanya', 'AdesanyaPyfer', 'MMA', 'UFCFightNight', 'MMABrasil', 'Stylebender', 'UFCPredictions'],
      best_posting_time: 'Quinta 18h (2 dias antes) ou Sabado 12h (dia do evento)',
    },
    tiktok: {
      meta: {
        algorithm_tip: 'Em 2026, voce precisa de 70%+ de retencao. Hooks sobre ex-campeoes em declinio e "ultima chance" geram curiosidade massiva. Rewatches > likes.',
        target_metric: '70%+ retencao, 5%+ taxa de save/share',
        content_type: '4 scripts de 45-90 segundos',
      },
      scripts: [
        {
          script_number: 1,
          angle: 'A Queda de Izzy',
          hook_3s: 'O cara que era INVENCIVEL no UFC perdeu 3 lutas SEGUIDAS.',
          body: 'Israel Adesanya. Bicampeao. 5 defesas de titulo. 13 knockdowns, recorde da divisao empatado com Anderson Silva. De 2019 a 2023, ninguem no peso-medio chegava perto. Ai veio Strickland. Decisao. Du Plessis. Submissao no R4. Imavov. TKO no R2. TRES derrotas seguidas. 13 meses sem lutar. 36 anos. E agora enfrenta Joe Pyfer, que tem 29 anos, 3 vitorias seguidas, e 1.2 knockdowns por 15 minutos. A pergunta: Izzy ainda e o Stylebender? Ou e o final de uma era?',
          twist_or_loop: 'Terminar com montagem: Izzy nocauteando Whittaker vs Izzy sendo nocauteado por Imavov. O contraste gera rewatch.',
          cta: 'Izzy volta ou e o fim? Comenta!',
          estimated_duration: '55-70s',
        },
        {
          script_number: 2,
          angle: 'A Revanche de 5 Anos',
          hook_3s: 'Ela perdeu essa luta em 2021. Agora volta com 7 VITORIAS SEGUIDAS.',
          body: 'Em 2021, Maycee Barber, 22 anos, vindo de uma lesao no joelho, perdeu por decisao pra Alexa Grasso. Rapido pra 2026: Barber tem SETE vitorias seguidas. Grasso perdeu o titulo de campeao e veio de 2 derrotas. As trajetorias se inverteram COMPLETAMENTE. A Barber de 2026 nao e a mesma de 2021. Revanche no sabado em Seattle.',
          cta: 'Barber vinga a derrota ou Grasso surpreende de novo? Comenta!',
          estimated_duration: '40-50s',
        },
        {
          script_number: 3,
          angle: 'A Aposentadoria em Casa',
          hook_3s: 'Esse cara esta lutando a ULTIMA luta da carreira dele. Em casa.',
          body: 'Michael Chiesa. Seattle, Washington. 19-7 na carreira. Anunciou que essa e a ultima luta. Em casa. No Climate Pledge Arena. Vem de 3 vitorias seguidas sobre Tony Ferguson, Max Griffin e Court McGee. Contra Niko Price, que aceitou em short notice e esta 2-7 nos ultimos anos. O adeus perfeito pra um veterano que nunca foi campeao mas sempre foi guerreiro.',
          cta: 'Chiesa merece uma aposentadoria com vitoria? Comenta!',
          estimated_duration: '40-50s',
        },
        {
          script_number: 4,
          angle: 'O Power Puncher vs O Stylebender',
          hook_3s: 'Esse cara tem 1.2 knockdowns por 15 minutos. E vai enfrentar um ex-campeao em declinio.',
          body: 'Joe Pyfer. Bodybagz. 15-3. 3 vitorias seguidas incluindo KO sobre Barriault e sub sobre Magomedov. 1.2 knockdowns por 15 minutos, top 4 do peso-medio. Contra Israel Adesanya que tem 13 knockdowns no UFC mas levou TKO e submissao nas ultimas 2. Pyfer e mais jovem, mais forte, e esta em ascensao. Izzy e mais tecnico, mais experiente, mas esta em queda. Juventude vs Legado.',
          cta: 'Pyfer nocauteia o ex-campeao? Comenta!',
          estimated_duration: '45-55s',
        },
      ],
    },
    youtube: {
      meta: {
        algorithm_tip: 'Videos sobre ex-campeoes voltando tem CTR altissimo. Thumbnails com "?" e expressoes de duvida. Titulos com "last chance" ou "is he done" geram cliques.',
        target_metric: '12%+ CTR, 50%+ retencao em 30s',
        content_type: 'Video de 10-12 minutos com timestamps',
      },
      title_options: [
        'Adesanya ACABOU? 3 Derrotas Seguidas e o Teste Final em Seattle',
        'UFC Seattle: O Ex-Campeao, a Revanche, e a Aposentadoria (Card Completo)',
        'Adesanya vs Pyfer: Legado vs Juventude no Peso-Medio',
      ],
      thumbnail: {
        headline: 'ACABOU?',
        subtext: 'Adesanya 3 derrotas',
        visual_concept: 'Adesanya com expressao seria/triste, fundo vermelho escurecendo. Pyfer menor ao lado, postura agressiva. "ACABOU?" em amarelo gigante. Record "L L L" em vermelho.',
      },
      description: 'Analise completa do UFC Seattle: Adesanya voltando de 3 derrotas contra Pyfer, Grasso vs Barber revanche de 5 anos, Chiesa se aposentando em casa, e todas as 13 lutas.\n\nTimestamps abaixo.',
      script_sections: [
        { timestamp: '0:00', title: 'Hook', text: 'Israel Adesanya era invencivel. Bicampeao. 5 defesas. 13 knockdowns, recorde empatado com Anderson Silva. E nos ultimos 2 anos, perdeu TRES lutas seguidas. No sabado, ele volta contra um power puncher de 29 anos que esta em ascensao. Essa pode ser a ultima chance de Izzy provar que o Stylebender ainda existe.', retention_note: 'Open loop: "e essa nem e a historia mais dramatica do card."', b_roll: 'Montagem: Izzy como campeao > as 3 derrotas em sequencia > Pyfer nocauteando.' },
        { timestamp: '0:45', title: 'Adesanya: A Queda', text: 'Strickland tirou o titulo por decisao. Du Plessis submeteu no R4. Imavov nocauteou no R2. 13 meses sem lutar. 36 anos. A narrativa e clara: Izzy nao e mais o mesmo. Mas ele disse que nao esta perseguindo o titulo, esta lutando com liberdade de novo. Pyfer e o teste perfeito: jovem, agressivo, com poder real.', b_roll: 'Highlights das 3 derrotas, entrevista recente de Adesanya sobre mindset.' },
        { timestamp: '2:30', title: 'Pyfer: O Teste', text: 'Joe Pyfer, 15-3, 29 anos. Nocauteou Barriault no R1 no UFC 303. Venceu Gastelum por decisao com 2 knockdowns. Submeteu Magomedov no R2 com face crank. 3 vitorias seguidas, 2 bonus de Performance. 1.2 knockdowns por 15 minutos. O cara tem poder. Mas nunca enfrentou alguem do nivel de Adesanya, mesmo em declinio.', b_roll: 'Highlights de Pyfer, KO sobre Barriault, sub sobre Magomedov.' },
        { timestamp: '4:00', title: 'Grasso vs Barber: A Revanche', text: 'Em 2021, Grasso venceu Barber por decisao. Desde entao, as trajetorias se inverteram. Grasso perdeu o titulo e 2 lutas seguidas. Barber ganhou 7 seguidas e e favorita -160. A Barber de 2026 nao e a mesma de 2021. Mas Grasso ja foi campeao e sabe competir no mais alto nivel.', b_roll: 'Highlights da primeira luta, timeline das carreiras.' },
        { timestamp: '5:30', title: 'Chiesa: O Adeus', text: 'Chiesa se aposenta em casa em Seattle. 19-7, 3 vitorias seguidas. Contra Price em short notice. E o tipo de luta emocional que faz o publico chorar. Espere uma performance motivada.', b_roll: 'Chiesa com a torcida de Seattle, momentos emotivos.' },
        { timestamp: '6:30', title: 'Resto do Card', text: 'McKinney tem 100% finish rate e promete nocaute rapido contra Nelson. Abdul-Malik vs Belgaroui e a pick em fight do card. Musayev, ex-campeao RIZIN com 18 KOs, busca sua primeira vitoria UFC. Erosa luta em casa contra o invicto Douglas.', b_roll: 'Quick montage de cada luta.' },
        { timestamp: '8:30', title: 'Previsoes e CTA', text: 'Minhas picks pra todas as 13 lutas estao na tela agora. O main event e o mais dificil de prever porque Adesanya em declinio e ainda mais perigoso. Eu vou com Izzy por decisao. Mas Pyfer por KO nao seria surpresa. Comenta sua pick e segue pra cobertura completa.', b_roll: 'Tela de picks, graficos de probabilidade.' },
      ],
      tags: ['UFC', 'UFC Seattle', 'Adesanya vs Pyfer', 'Israel Adesanya', 'Joe Pyfer', 'UFC Fight Night', 'MMA', 'Alexa Grasso', 'Maycee Barber', 'Michael Chiesa'],
    },
    twitter: {
      meta: {
        algorithm_tip: 'Replies valem 150x mais que likes. Threads sobre ex-campeoes em declinio geram debate enorme. Hot takes sobre "is he done" geram replies massivos.',
        target_metric: '5%+ taxa de reply',
        content_type: 'Thread de 10 tweets + 3 tweets avulsos + enquete',
      },
      thread: [
        { num: '1/10', text: 'UFC Seattle no sabado: Adesanya voltando de 3 derrotas, Grasso vs Barber revanche, e Chiesa se aposentando em casa. Card STACKED. Thread completa:', tweet_type: 'hook', engagement_note: 'Nomes grandes geram saves imediatos.' },
        { num: '2/10', text: 'MAIN EVENT: Adesanya (24-5) vs Pyfer (15-3). Izzy perdeu 3 seguidas (Strickland, Du Plessis, Imavov). 13 meses parado. 36 anos. Pyfer vem de 3 vitorias com 2 bonus. 29 anos. Power puncher com 1.2 knockdowns/15min. Legado vs Juventude.', tweet_type: 'content' },
        { num: '3/10', text: 'Hot take: Adesanya AINDA e mais tecnico que qualquer peso-medio do UFC. As 3 derrotas foram contra top 5. Pyfer nunca enfrentou alguem desse nivel. Se Izzy manter distancia e usar o jab, Pyfer nao tem resposta. Pick: Adesanya por decisao.', tweet_type: 'hot_take', engagement_note: 'Ir a favor de Adesanya contra a narrativa de declinio gera debate.' },
        { num: '4/10', text: 'CO-MAIN: Grasso vs Barber II. Em 2021, Grasso venceu. Desde entao: Grasso perdeu titulo + 2 lutas. Barber: 7 vitorias seguidas. As trajetorias se inverteram COMPLETAMENTE. Barber favorita -160. Pick: Barber por decisao.', tweet_type: 'content' },
        { num: '5/10', text: 'A APOSENTADORIA: Chiesa em casa em Seattle. 19-7, 3 vitorias seguidas. Contra Price (2-7 nos ultimos anos) em short notice. O adeus do Maverick. Espere emocao. Pick: Chiesa por decisao dominante.', tweet_type: 'content' },
        { num: '6/10', text: 'McKinney tem 100% finish rate. NUNCA foi a decisao (vitoria ou derrota). Nelson vem de 4 em 5 no UFC. Esse e o tipo de luta que acaba em 90 segundos. Pick: McKinney KO R1.', tweet_type: 'content' },
        { num: '7/10', text: 'PICK EM DO CARD: Abdul-Malik (9-0-1) vs Belgaroui. Basicamente 50/50 nas odds. Abdul-Malik tem wrestling D1 mas Belgaroui treina com Alex Pereira e tem tamanho (1,96m). Minha pick: Belgaroui pela envergadura e a experiencia recente contra wrestlers.', tweet_type: 'content' },
        { num: '8/10', text: 'PRELIM DESTAQUE: Musayev, ex-campeao RIZIN com 18 KOs em 22 vitorias, busca a primeira vitoria UFC. Perdeu o debut por sub R1. Contra Bahamondes que tem 3 finishes no R1 seguidos. Explosivo vs Explosivo. Pick: Bahamondes.', tweet_type: 'content' },
        { num: '9/10', text: 'PRELIMS RAPIDAS:\nHooper por sub R2\nFortune por decisao\nO\'Neill por decisao\nStirling por decisao\nYanez por KO R2\nBrasil por decisao\n\n7 prelims, 4 devem ir a decisao.', tweet_type: 'content' },
        { num: '10/10', text: 'A pergunta do card: Adesanya AINDA tem nivel de elite ou as 3 derrotas sao o comeeo do fim? Responde com o que voce acha. Vamos debater antes de sabado.', tweet_type: 'cta', engagement_note: 'Pergunta sobre legado de ex-campeao gera replies massivos.' },
      ],
      standalone_tweets: [
        'Adesanya tem 13 knockdowns no UFC, empatado com Anderson Silva. Mas perdeu 3 seguidas e esta com 36 anos. No sabado, enfrenta um power puncher de 29 anos. A pergunta nao e se Izzy e bom. E se ele AINDA e bom.',
        'Grasso venceu Barber em 2021. Desde entao: Grasso perdeu titulo e 2 lutas. Barber ganhou 7 seguidas. As trajetorias se inverteram completamente em 5 anos. A revanche mais justa do UFC.',
        'Chiesa anunciou que sabado e a ultima luta. Em casa, em Seattle. 19-7, 3 vitorias seguidas. Independente do resultado, o cara merece uma ovacao de pe.',
      ],
      poll_suggestion: {
        question: 'Adesanya vence Pyfer no sabado?',
        options: ['Sim, Izzy por decisao', 'Sim, Izzy por KO', 'Nao, Pyfer por KO', 'Nao, Pyfer por decisao/sub'],
      },
    },
    podcast: {
      meta: {
        algorithm_tip: 'Episodios sobre ex-campeoes voltando sao os mais ouvidos. Hot takes sobre "e o fim?" geram comentarios. Momentos clipaveis com opinioes fortes geram shorts.',
        target_metric: '70%+ retencao, 3+ momentos clipaveis',
        content_type: 'Episodio de 35-45 minutos com 6 segmentos',
      },
      episode_title: 'UFC Seattle: O Ex-Campeao, a Revanche, e a Aposentadoria',
      episode_description: 'Adesanya voltando de 3 derrotas contra Pyfer. Grasso vs Barber revanche de 5 anos com trajetorias invertidas. Chiesa se aposentando em casa em Seattle. McKinney prometendo mais um finish rapido. Analise completa de todas as 13 lutas.',
      cold_open: 'Treze knockdowns. Empatado com Anderson Silva. Bicampeao. Cinco defesas de titulo. E nos ultimos dois anos, tres derrotas seguidas. A pergunta sobre Israel Adesanya nao e se ele foi grande. E se ele AINDA e. No sabado em Seattle, um power puncher de 29 anos vai dar a resposta.',
      segments: [
        {
          timestamp: '0:00-8:00',
          title: 'Adesanya vs Pyfer: Legado vs Juventude',
          talking_points: [
            'A queda de Izzy: de invencivel pra 3 derrotas seguidas. Strickland por decisao (surpresa), Du Plessis por sub R4 (desgaste), Imavov por TKO R2 (velocidade). Cada derrota expoe algo diferente.',
            'O mindset novo: Adesanya disse que nao esta perseguindo o titulo. Esta lutando com liberdade. Isso e bom (menos pressao) ou ruim (menos urgencia)?',
            'Pyfer como teste: 15-3, 3 vitorias seguidas, 2 bonus POTN. Power puncher com 1.2 knockdowns por 15 min. Mas nunca enfrentou alguem do nivel de Adesanya, mesmo em declinio.',
            'A tese: Adesanya AINDA e mais tecnico que Pyfer. O jab, o timing, o fight IQ. Se mantiver distancia, Pyfer nao tem resposta. O risco: se Pyfer entrar e conectar, o queixo de Izzy pode nao aguentar.',
          ],
          quotable_moment: 'Adesanya em declinio AINDA e mais tecnico que 90% do peso-medio. O problema e que ele nao esta enfrentando 90% do peso-medio. Esta enfrentando caras que podem machuca-lo.',
          hot_take: 'Adesanya vence por decisao. O mundo MMA quer a narrativa do fim, mas Izzy contra um cara que nunca enfrentou elite e diferente de Izzy contra Du Plessis. Pyfer vai ser sobreparedado tecnicamente.',
          discussion_questions: [
            'Se Adesanya perder, voces acham que ele deveria se aposentar?',
            'Pyfer e o oponente certo pra testar se Izzy ainda tem nivel, ou e facil demais?',
          ],
        },
        {
          timestamp: '8:00-13:00',
          title: 'Grasso vs Barber: A Revanche de 5 Anos',
          talking_points: [
            'Em 2021, Grasso venceu por decisao quando Barber tinha 22 anos e vinha de lesao no joelho. Contexto importa.',
            'Trajetorias invertidas: Grasso subiu (titulo), caiu (perdeu titulo, 2 derrotas). Barber subiu consistentemente (7 vitorias seguidas).',
            'Barber favorita -160 mas Grasso ja foi campeao e tem experiencia de 5 rounds contra Shevchenko. Nao e facil descartar.',
            'Pick: Barber por decisao. A versao 2026 dela e atleticamente superior e o momentum e real.',
          ],
          discussion_questions: [
            'Grasso consegue repetir 2021 ou Barber evoluiu demais?',
          ],
        },
        {
          timestamp: '13:00-17:00',
          title: 'Chiesa: O Adeus em Casa',
          talking_points: [
            'Chiesa anunciou aposentadoria. Em casa, em Seattle. Emocional.',
            'Vem de 3 vitorias seguidas: Ferguson, Griffin, McGee. Quer sair por cima.',
            'Price em short notice (substituiu Harris) e 2-7 nos ultimos anos. Luta favoravel pro adeus.',
            'O tipo de noite que faz o publico chorar. Independente do resultado.',
          ],
          quotable_moment: 'Chiesa nunca foi campeao. Nunca foi favorito da midia. Mas sempre foi guerreiro. Em Seattle, em casa, o Maverick merece o adeus que ele quer.',
        },
        {
          timestamp: '17:00-22:00',
          title: 'Main Card: Erosa, Abdul-Malik, McKinney',
          talking_points: [
            'McKinney: 100% finish rate, NUNCA foi a decisao. Contra Nelson que vem de 4 em 5. Luta que promete fogo e deve acabar rapido.',
            'Abdul-Malik vs Belgaroui: a pick em fight. 50/50 nas odds. Abdul-Malik tem wrestling D1 mas Belgaroui treina com Alex Pereira e venceu um wrestler recentemente.',
            'Erosa vs Douglas: veterano da casa contra debutante invicto. Erosa em Seattle e perigoso. Douglas tem poder mas nunca lutou no UFC.',
          ],
          discussion_questions: [
            'McKinney consegue manter o 100% finish rate contra Nelson?',
          ],
        },
        {
          timestamp: '22:00-28:00',
          title: 'Prelims e Previsoes Completas',
          talking_points: [
            'Musayev vs Bahamondes: ex-campeao RIZIN com 18 KOs busca primeira vitoria UFC. Bahamondes com 3 finishes no R1 seguidos. A prelim mais explosiva.',
            'Simon vs Yanez: dois strikers de elite no peso-galo. Yanez tem poder pra acabar. Simon tem wrestling pra controlar.',
            'Hooper vs Gibson Jr: jiu-jitsu de elite contra filho de lenda do MMA canadense.',
            'Todas as 13 picks: Adesanya UD, Barber UD, Chiesa UD, Erosa UD, Belgaroui UD, McKinney KO R1, Bahamondes KO R2, Hooper Sub R2, Fortune UD, O\'Neill UD, Stirling UD, Yanez KO R2, Brasil UD.',
          ],
        },
        {
          timestamp: '28:00-32:00',
          title: 'Encerramento',
          talking_points: [
            'O card e sobre narrativas: o ex-campeao buscando redencao, a revanche de 5 anos, a aposentadoria emotiva. Tudo em Seattle.',
            'Depois do evento: recap completo com accuracy audit, model autopsy, e creator kit pos-evento.',
            'Se voce so pode assistir 3 lutas: Adesanya/Pyfer, Grasso/Barber, e Jones/Sola de Londres que foi a guerra do ano. Wait, McKinney/Nelson promete ser rapida e brutal.',
          ],
          quotable_moment: 'Esse card e sobre perguntas que so o octogono responde. Adesanya ainda e elite? Barber evoluiu o suficiente? Chiesa merece o final feliz? Sabado a noite, Seattle responde.',
          discussion_questions: [
            'Qual e a luta que voces estao mais ansiosos pra ver?',
          ],
        },
      ],
    },
  } as EventCreatorKitData,
};

export default async function Page() {
  
  
  const enrichedData = await enrichEventWithPhotos(translateAnalysis(eventData));
  return <EventAnalysisView data={enrichedData} />;
}
