import { PrelimsAnalysisView } from '@/components/analise/PrelimsAnalysisView';
import type { PrelimsAnalise } from '@/types/analise';

const analise: PrelimsAnalise = {
  id: 'jones-vs-sola',
  evento_id: null,
  slug: 'jones-vs-sola',
  titulo: 'Jones vs Sola',
  subtitulo: null,
  lutador1_id: null,
  lutador2_id: null,
  artigo_conteudo: '',
  tactical_breakdown: {
    stats: [],
    radarData: [],
    taleOfTape: {
      fighter1: { altura: '', envergadura: '', idade: 0, academia: '' },
      fighter2: { altura: '', envergadura: '', idade: 0, academia: '' },
    },
    pathsToVictory: { fighter1: [], fighter2: [] },
    dangerZones: [],
  },
  fight_prediction: {
    predictedWinner: 'fighter1',
    predictedMethod: 'Decisao Unanime',
    confidence: 'MEDIA',
    fighter1Scenarios: [],
    fighter2Scenarios: [],
    keyFactors: [],
    xFactor: { title: '', description: '' },
  },
  fighter1_info: {
    nome: 'Mason Jones',
    record: '17-2-0',
    ultimasLutas: [],
  },
  fighter2_info: {
    nome: 'Axel Sola',
    record: '11-0-1',
    ultimasLutas: [],
  },
  evento_nome: 'UFC Fight Night: Evloev vs Murphy',
  evento_data: '21 de Marco, 2026',
  evento_local: 'The O2 Arena, Londres, Reino Unido',
  categoria_peso: 'Peso Leve (155 lbs)',
  num_rounds: 3,
  is_titulo: false,
  broadcast: null,
  status: 'published',
  analysis_type: 'prelims',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),

  prelims_analysis: {
    hero: {
      evento_nome: 'UFC Fight Night: Evloev vs Murphy',
      evento_data: '21 de Marco, 2026',
      categoria_peso: 'Peso Leve (155 lbs)',
      num_rounds: 3,
      is_titulo: false,
      fighter1: {
        nome: 'Jones',
        record: '17-2-0',
        ranking: undefined,
      },
      fighter2: {
        nome: 'Sola',
        record: '11-0-1',
        ranking: undefined,
      },
    },

    comparacao_estatistica: {
      stats: [
        {
          label: 'Sig. Strikes por Minuto',
          valueA: 5.61,
          valueB: 5.16,
          maxVal: 8,
          format: 'decimal',
          note: 'Ambos com volume altissimo de strikes, luta tende a ser uma guerra em pe',
        },
        {
          label: 'Precisao de Strikes (%)',
          valueA: 44,
          valueB: 44,
          maxVal: 100,
          format: 'percent',
          note: 'Precisao identica, os dois acertam quase metade dos golpes',
        },
        {
          label: 'Strikes Absorvidos/Min',
          valueA: 4.52,
          valueB: 3.88,
          maxVal: 7,
          format: 'decimal',
          reverseWinner: true,
          note: 'Jones absorve mais golpes, ficou perto de ser finalizado por Oki no R1',
        },
        {
          label: 'Defesa de Strikes (%)',
          valueA: 52,
          valueB: 56,
          maxVal: 100,
          format: 'percent',
          note: 'Defesa de strikes abaixo da media para ambos, luta aberta',
        },
        {
          label: 'Takedowns por 15 Min',
          valueA: 2.75,
          valueB: 1.20,
          maxVal: 5,
          format: 'decimal',
          note: 'Jones usa o wrestling como arma principal quando a trocacao complica',
        },
        {
          label: 'Precisao de Takedown (%)',
          valueA: 45,
          valueB: 33,
          maxVal: 100,
          format: 'percent',
        },
        {
          label: 'Defesa de Takedown (%)',
          valueA: 80,
          valueB: 65,
          maxVal: 100,
          format: 'percent',
          note: 'Jones tem defesa de takedown elite, dificil de derrubar',
        },
      ],
      tale_of_tape: [
        { label: 'Idade', fighter1: '30 anos', fighter2: '28 anos', note: null },
        { label: 'Altura', fighter1: '1,78m (5\'10")', fighter2: '1,88m (6\'2")', note: 'Sola tem 10cm de vantagem na altura' },
        { label: 'Envergadura', fighter1: '188cm (74")', fighter2: '188cm (74")', note: 'Envergadura identica apesar da diferenca de altura' },
        { label: 'Stance', fighter1: 'Ortodoxo', fighter2: 'Canhoto', note: 'Dinamica ortodoxo vs southpaw' },
        { label: 'Academia', fighter1: 'Composed MMA / Pais de Gales', fighter2: 'Boxing Squad / Nice, Franca', note: null },
      ],
    },

    historico_lutas: {
      fighter1: {
        nome: 'Jones',
        recent_fights: [
          {
            date: 'Set 2025',
            opponent: 'Bolaji Oki',
            result: 'W',
            method: 'TKO R2 (cotoveladas)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Quase foi finalizado no R1, mas voltou devastador com quedas e cotoveladas no R2. Performance of the Night.',
          },
          {
            date: 'Mai 2025',
            opponent: 'Jeremy Stephens',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Dominou com wrestling nos rounds finais contra veterano da divisao no retorno ao UFC.',
          },
          {
            date: 'Jul 2024',
            opponent: 'Michael Pagani',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Vitoria no Cage Warriors antes de retornar ao UFC, controle total por 3 rounds.',
          },
          {
            date: 'Jul 2022',
            opponent: 'Ludovit Klein',
            result: 'L',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 3,
            quality_label: 'Bom',
            note: 'Dominado por 3 rounds em Londres, resultado que levou Jones a sair do UFC temporariamente.',
          },
          {
            date: 'Out 2021',
            opponent: 'David Onama',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Primeira vitoria no UFC contra prospect que depois se destacou na divisao.',
          },
        ],
      },
      fighter2: {
        nome: 'Sola',
        recent_fights: [
          {
            date: 'Set 2025',
            opponent: 'Rhys McKee',
            result: 'W',
            method: 'TKO R3 (soco no corpo)',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Estreia no UFC impressionante. Dobrou McKee com soco no corpo devastador no terceiro round.',
          },
          {
            date: 'Jun 2025',
            opponent: 'Soslan Gagloev',
            result: 'W',
            method: 'Decisao Unanime',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Defesa do titulo ARES FC, entregou primeira derrota da carreira de Gagloev.',
          },
          {
            date: 'Dez 2024',
            opponent: 'Daguir Imavov',
            result: 'D',
            method: 'Empate Majoritario',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Defesa de titulo no ARES FC, luta extremamente competitiva que terminou empatada.',
          },
          {
            date: 'Jun 2024',
            opponent: 'Yurpal Younousov',
            result: 'W',
            method: 'TKO R3',
            opponent_rank: 'N/R',
            quality_score: 2,
            quality_label: 'Medio',
            note: 'Conquistou o titulo vago do ARES FC parando Younousov no terceiro round.',
          },
          {
            date: 'Mar 2024',
            opponent: 'Cesar Arzamendia',
            result: 'W',
            method: 'TKO R1',
            opponent_rank: 'N/R',
            quality_score: 1,
            quality_label: 'Ruim',
            note: 'Finalizacao rapida na estreia pelo ARES FC, nocaute no primeiro round.',
          },
        ],
      },
    },

    perfil_habilidades: {
      skills: [
        {
          label: 'Striking em Pe',
          valueA: 78,
          valueB: 76,
          labelA: 'Muito Bom',
          labelB: 'Muito Bom',
          advantage: 'even',
          advantage_note: 'Ambos sao excelentes strikers com volume alto. Jones tem mais experiencia no UFC, Sola traz poder no corpo.',
        },
        {
          label: 'Poder de Nocaute',
          valueA: 72,
          valueB: 78,
          labelA: 'Bom',
          labelB: 'Muito Bom',
          advantage: 'fighter2',
          advantage_note: 'Sola tem 55% de vitorias por KO/TKO, incluindo nocaute por soco no corpo no UFC. Jones finaliza mais no chao.',
        },
        {
          label: 'Wrestling Ofensivo',
          valueA: 80,
          valueB: 55,
          labelA: 'Muito Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Jones dominou Stephens e Oki com quedas e controle. Sua principal arma quando a trocacao complica.',
        },
        {
          label: 'Defesa e Grappling',
          valueA: 75,
          valueB: 60,
          labelA: 'Muito Bom',
          labelB: 'Bom',
          advantage: 'fighter1',
          advantage_note: 'Jones tem 80% de defesa de takedown e e perigoso no chao com cotoveladas. Sola ainda nao foi testado nesse aspecto no UFC.',
        },
        {
          label: 'Cardio e Ritmo',
          valueA: 72,
          valueB: 76,
          labelA: 'Bom',
          labelB: 'Muito Bom',
          advantage: 'fighter2',
          advantage_note: 'Sola mantem pressao constante e tem experiencia em lutas de 5 rounds como campeao ARES. Jones as vezes desacelera.',
        },
        {
          label: 'Experiencia no Octagon',
          valueA: 72,
          valueB: 40,
          labelA: 'Bom',
          labelB: 'Medio',
          advantage: 'fighter1',
          advantage_note: 'Jones tem 6 lutas no UFC (4V-2D) incluindo retorno triunfal. Sola tem apenas 1 luta no Octagon.',
        },
      ],
      insight: 'Jones e o lutador mais completo com wrestling superior e experiencia no UFC, enquanto Sola compensa com poder de finalizacao e ritmo incansavel. A chave da luta e se Jones consegue levar para o chao ou se Sola mantem a distancia com seu jab e ataques ao corpo.',
    },

    distribuicao_vitorias: {
      fighter1: {
        nome: 'Jones',
        ko_tko: { count: 8, percent: 47 },
        submission: { count: 3, percent: 18 },
        decision: { count: 6, percent: 35 },
        total_wins: 17,
      },
      fighter2: {
        nome: 'Sola',
        ko_tko: { count: 6, percent: 55 },
        submission: { count: 1, percent: 9 },
        decision: { count: 4, percent: 36 },
        total_wins: 11,
      },
      insight: 'Jones tem perfil mais versatil com vitorias divididas entre KO (47%), decisao (35%) e finalizacao (18%), mostrando capacidade de vencer de varias formas. Sola e mais dependente do poder, com 55% de nocautes e apenas 1 finalizacao. Se a luta for para o chao, Jones tem vantagem clara nas opcoes.',
    },

    previsao_final: {
      winner_name: 'Jones',
      winner_side: 'fighter1',
      predicted_method: 'Decisao Unanime',
      confidence_score: 5,
      confidence_label: 'MEDIA',
      explanation: 'Mason Jones tem a vantagem do wrestling e da experiencia no Octagon, dois fatores que costumam ser decisivos contra estreantes em ascensao. Sola e um prospecto perigoso com poder real nas maos e no corpo, mas ainda nao foi testado contra um grappler do nivel de Jones. O gales deve misturar wrestling com striking nos rounds 2 e 3 para acumular pontos nos cartoes. Porem, o poder de Sola e a dinamica southpaw tornam esta luta muito mais competitiva do que as odds sugerem.',
      x_factor: {
        title: 'O wrestling de Jones contra um striker',
        description: 'Jones provou contra Stephens e Oki que pode dominar rounds inteiros no chao. Se conseguir impor esse jogo contra Sola, que nunca enfrentou um wrestler desse calibre, a luta pode ser unilateral.',
      },
      upset_alert: {
        title: 'Sola tem poder para acabar a luta a qualquer momento',
        description: 'O frances dobrou Rhys McKee com um soco no corpo e tem 6 nocautes na carreira. Se Jones entrar descuidado na troca como fez no R1 contra Oki, Sola pode capitalizar com um unico golpe bem colocado.',
      },
      probabilities: {
        fighter1: { nome: 'Jones', percent: 54 },
        fighter2: { nome: 'Sola', percent: 44 },
        draw: 2,
      },
      value_picks: undefined,
    },
  },
};

export default function Page() {
  return <PrelimsAnalysisView analise={analise} />;
}
