import { EventAnalysisView, type EventAnalysisData } from '@/components/analise/EventAnalysisView';
import { enrichEventWithPhotos } from '@/lib/enrich-event-photos';

const eventData: EventAnalysisData = {
  evento_nome: 'UFC Fight Night: Emmett vs Vallejos',
  evento_data: '14 de Marco, 2026',
  evento_local: 'Meta APEX, Las Vegas, Nevada, EUA',
  main_card: [
    {
      slug: 'emmett-vs-vallejos',
      fighter1: { nome: 'Josh Emmett', record: '19-6-0' },
      fighter2: { nome: 'Kevin Vallejos', record: '17-1-0' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 5,
      predicted_winner: 'Kevin Vallejos',
      predicted_method: 'TKO R2-R3 ou Decisao Unanime',
      confidence_label: 'MEDIA-ALTA',
      is_main_event: true,
    },
    {
      slug: 'lemos-vs-robertson',
      fighter1: { nome: 'Amanda Lemos', record: '15-5-1' },
      fighter2: { nome: 'Gillian Robertson', record: '16-8-0' },
      categoria_peso: 'Peso Palha Feminino (115 lbs)',
      num_rounds: 3,
      predicted_winner: 'Gillian Robertson',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'cutelaba-vs-sy',
      fighter1: { nome: 'Ion Cutelaba', record: '19-11-1' },
      fighter2: { nome: 'Oumar Sy', record: '12-1-0' },
      categoria_peso: 'Peso Meio-Pesado (205 lbs)',
      num_rounds: 3,
      predicted_winner: 'Oumar Sy',
      predicted_method: 'TKO R2 ou Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'fili-vs-delgado',
      fighter1: { nome: 'Andre Fili', record: '25-12-0' },
      fighter2: { nome: 'Jose Miguel Delgado', record: '10-2-0' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Jose Miguel Delgado',
      predicted_method: 'TKO R1 ou R2',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'rahiki-vs-hardwick',
      fighter1: { nome: 'Marwan Rahiki', record: '7-0-0' },
      fighter2: { nome: 'Harry Hardwick', record: '13-4-1' },
      categoria_peso: 'Peso Pena (145 lbs)',
      num_rounds: 3,
      predicted_winner: 'Marwan Rahiki',
      predicted_method: 'KO/TKO nos dois primeiros rounds',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'petrino-vs-asplund',
      fighter1: { nome: 'Vitor Petrino', record: '13-2-0' },
      fighter2: { nome: 'Steven Asplund', record: '7-1-0' },
      categoria_peso: 'Peso Pesado (265 lbs)',
      num_rounds: 3,
      predicted_winner: 'Vitor Petrino',
      predicted_method: 'Submissao ou TKO por Ground-and-Pound',
      confidence_label: 'MEDIA-ALTA',
    },
  ],
  prelims: [
    {
      slug: 'johnson-vs-silva',
      fighter1: { nome: 'Charles Johnson', record: '18-8-0' },
      fighter2: { nome: 'Bruno Silva', record: '15-7-2' },
      categoria_peso: 'Peso Mosca (125 lbs)',
      num_rounds: 3,
      predicted_winner: 'Charles Johnson',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'tavares-vs-anders',
      fighter1: { nome: 'Brad Tavares', record: '21-12-0' },
      fighter2: { nome: 'Eryk Anders', record: '17-9-0, 1 NC' },
      categoria_peso: 'Peso Medio (185 lbs)',
      num_rounds: 3,
      predicted_winner: 'Brad Tavares',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'curtis-vs-orolbai',
      fighter1: { nome: 'Chris Curtis', record: '32-12-0, 1 NC' },
      fighter2: { nome: 'Myktybek Orolbai', record: '15-2-1' },
      categoria_peso: 'Peso Meio-Medio (170 lbs)',
      num_rounds: 3,
      predicted_winner: 'Myktybek Orolbai',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'oki-vs-sousa',
      fighter1: { nome: 'Bolaji Oki', record: '10-3-0' },
      fighter2: { nome: 'Manoel Sousa', record: '13-1-0' },
      categoria_peso: 'Peso Leve (155 lbs)',
      num_rounds: 3,
      predicted_winner: 'Manoel Sousa',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIA-ALTA',
    },
    {
      slug: 'lacerda-vs-sosa',
      fighter1: { nome: 'Luan Lacerda', record: '13-3-0' },
      fighter2: { nome: 'Hecher Sosa', record: '14-1-0' },
      categoria_peso: 'Peso Galo (135 lbs)',
      num_rounds: 3,
      predicted_winner: 'Hecher Sosa',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIA',
    },
    {
      slug: 'mesquita-vs-rendon',
      fighter1: { nome: 'Bia Mesquita', record: '6-0-0' },
      fighter2: { nome: 'Montse Rendon', record: '7-1-0' },
      categoria_peso: 'Peso Galo Feminino (135 lbs)',
      num_rounds: 3,
      predicted_winner: 'Bia Mesquita',
      predicted_method: 'Finalizacao R2',
      confidence_label: 'MEDIA-ALTA',
    },
    {
      slug: 'smith-vs-you',
      fighter1: { nome: 'Elijah Smith', record: '9-1-0' },
      fighter2: { nome: 'SuYoung You', record: '16-3-0, 2 NC' },
      categoria_peso: 'Peso Galo (135 lbs)',
      num_rounds: 3,
      predicted_winner: 'Elijah Smith',
      predicted_method: 'TKO R2',
      confidence_label: 'MEDIA-ALTA',
    },
    {
      slug: 'rodriguez-vs-hughes',
      fighter1: { nome: 'Piera Rodriguez', record: '11-2-0' },
      fighter2: { nome: 'Sam Hughes', record: '11-6-0' },
      categoria_peso: 'Peso Palha Feminino (115 lbs)',
      num_rounds: 3,
      predicted_winner: 'Piera Rodriguez',
      predicted_method: 'Decisao Unanime',
      confidence_label: 'MEDIA-ALTA',
    },
  ],
};

export default async function EventoEmmettVsVallejosPage() {
  const enrichedData = await enrichEventWithPhotos(eventData);
  return <EventAnalysisView data={enrichedData} />;
}
